/*************************************************************************
 * Decompiled by ATE47 and Edited by SyndiShanX
 * Script: scripts\mp\maps\mp_piccadilly\mp_piccadilly_create_script.gsc
*************************************************************************/

function main(var0, var1) {
  level endon("game_ended");

  if(scripts\engine\utility::flag_exist("mp_piccadilly_create_script")) {
    return;
  }

  scripts\engine\utility::flag_init("mp_piccadilly_create_script");
  var2 = spawnStruct();
  thread cs_return_and_wait_for_flag(level, var0, var1, var2);

  if(!scripts\cp\so_trigger::cs_is_starttime()) {
    scripts\cp\so_trigger::endcreatescript(var2);
    return;
  }
}

function cs_return_and_wait_for_flag(var0, var1, var2, var3) {
  scripts\cp\so_trigger::wait_for_cs_flag(var3);

  if(!isDefined(var1)) {
    var1 = "stk";
  }

  var2 scripts\cp\so_trigger::strike_setup_arrays(var1, "mp_piccadilly_create_script");
  scripts\cp\so_trigger::cs_init_flags(var2);
  thread createstructs(level, var2, var1);
  thread createtriggers(level, var2, var1);

  if(istrue(var0)) {
    level thread scripts\cp\so_trigger::wait_for_flags(var2, "mp_piccadilly_create_script");
    return;
  }

  scripts\cp\so_trigger::wait_for_flags(var2, "mp_piccadilly_create_script");
}

function createstructs(var0, var1, var2) {
  var3 = &scripts\cp\so_trigger::strike_additem;
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-215, 315, 260.5), (0, 132.47, 0), "trial_waypoint_knife", undefined, "12", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2413.64, 711.07, 202), (360, 174, 180), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (696, 142, 308), (0, 199, 0), "trial_waypoint_knife", undefined, "14", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (1316, 336, 210), (0, 262.99, 0), "trial_waypoint_knife", undefined, "15", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (1788, 602, 216), (0, 276.99, 0), "trial_waypoint_knife", undefined, "17", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (1750, 1130, 252), (0, 176.99, 0), "trial_waypoint_knife", undefined, "18", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1500, -605, 133), (0, 176, 0), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-1745.5, 87.5, 183.75), (0, 108.41, 0), "trial_waypoint_knife", undefined, "4", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "uk_gas_tank_thin_cylinder_2_destr";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (7, 124.2, 126), (310, 206, -90), "trial_gascanister", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1313.75, -129.25, 174.5), (90, 235.2, -169.8), undefined, undefined, "trial_vfx_gas_emit", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-252.87, 254.91, 165.45), (56.61, 275.62, -135), undefined, undefined, "trial_vfx_gas_emit", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-248.75, 188, 139), (-90, 235.2, -169.8), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "uk_gas_tank_thin_cylinder_2_cracked";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-250.28, 228.63, 125.38), (337.1, 325.76, -24.99), "trial_gascanister", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1454.02, -341.12, 142), (0, 0, 0), undefined, undefined, "trial_vfx_gas_linger_lg", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "uk_gas_tank_thin_cylinder_2_destr";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1498, -605, 132), (310, 85, -90), "trial_gascanister", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (1646, 648, 128), (0, 348, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (1595, 659, 128), (0, 348, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (2237, 1303, 131), (0, 360, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-2192, 760, 256.5), (0, 121.8, 0), "trial_waypoint_knife", undefined, "2", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-1858.5, 297.75, 225), (0, 113.75, 0), "trial_waypoint_knife", undefined, "3", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-1687.25, -116.25, 259.75), (0, 92.68, 0), "trial_waypoint_knife", undefined, "5", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-1683.25, -480, 257.25), (0, 130.63, 0), "trial_waypoint_knife", undefined, "6", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-1412.75, -720.75, 292.25), (0, 176, 0), "trial_waypoint_knife", undefined, "7", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (8.75, 123.23, 127), (0, 297, 0), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "uk_gas_tank_thin_cylinder_2_destr";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (1439, 564.2, 130), (310, 246, -90), "trial_gascanister", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (1440.75, 563.23, 131), (0, 337, 0), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (1007.48, 404.13, 128), (0, 0, 0), undefined, undefined, "trial_vfx_gas_linger_lg", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (2185, 1303, 131), (0, 360, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (2231, 1303, 186), (0, 360, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-1096, -715.25, 289), (0, 235.5, 0), "trial_waypoint_knife", undefined, "8", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "highway_flag0";
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (2208, 972, 322), (0, 285, 0), "trial_waypoint_knife", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-558, 193.75, 277.75), (0, 201.91, 0), "trial_waypoint_knife", undefined, "11", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1312.75, -130.25, 134.5), (-90, 235.2, -169.8), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "uk_gas_tank_thin_cylinder_2_cracked";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1313.75, -129.25, 126.5), (0, 315, 0), "trial_gascanister", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-690.5, 173.75, 173), (90, 345.73, -105.65), undefined, undefined, "trial_vfx_gas_emit", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (130, 82, 256), (0, 185, 0), "trial_waypoint_knife", undefined, "13", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-432.5, -122.25, 133), (-90, 235.2, -169.8), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "uk_gas_tank_thin_cylinder_2_cracked";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-690.5, 173.75, 125), (0, 1.38, 0), "trial_gascanister", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2074, 436, 147), (0, 216, 0), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "uk_gas_tank_thin_cylinder_2_destr";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2072, 436, 146), (310, 125, -90), "trial_gascanister", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1694.52, 598.13, 148), (0, 0, 0), undefined, undefined, "trial_vfx_gas_linger_lg", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1486.52, 158.13, 130), (0, 0, 0), undefined, undefined, "trial_vfx_gas_linger_lg", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1853.52, -437.87, 138), (0, 0, 0), undefined, undefined, "trial_vfx_gas_linger_lg", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-641, -317, 131), (-90, 235.2, -169.8), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1059, -503, 121), (-90, 235.2, -169.8), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (231.48, -329.87, 124), (0, 0, 0), undefined, undefined, "trial_vfx_gas_linger_lg", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (951.5, 433.25, 170.25), (90, 235.2, -169.8), undefined, undefined, "trial_vfx_gas_emit", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (964.25, -22.25, 125), (-90, 235.2, -169.8), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (2208, 972, 326), (0, 90, 0), "trial_waypoint_knife", undefined, "19", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "uk_gas_tank_thin_cylinder_2_cracked";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (951.5, 433.25, 122.25), (0, 315, 0), "trial_gascanister", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (1615.48, 932.13, 142), (0, 0, 0), undefined, undefined, "trial_vfx_gas_linger_lg", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (2187.48, 1450.13, 142), (0, 0, 0), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (1850, 798, 181), (90, 235.2, -169.8), undefined, undefined, "trial_vfx_gas_emit", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (1851, 797, 141), (-90, 235.2, -169.8), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "uk_gas_tank_thin_cylinder_2_cracked";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (1850, 798, 133), (0, 315, 0), "trial_gascanister", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "uk_gas_tank_thin_cylinder_2_destr";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (2047, 1132.2, 136), (310, 65.99, -90), "trial_gascanister", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (2048.75, 1131.23, 137), (0, 157, 0), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "storage_shelf_beam_wood_plank";
  var0[[var3]](var4, var1, var2, (-1614.25, -514.75, 263), (360, 41, -7.5), "trial_plank_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1947, 395, 148), (0, 348, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1174, 19, 137), (0, 330.3, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-2412, 710, 203), (0, 198, 0), "trial_waypoint_knife", undefined, "1", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "automotive_truck_loading_ramp_short";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2507.68, 550.32, 194), (0, 45, 0), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_wheel_back_lm";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2626.12, 488.45, 168), (0, 45, 0), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_wheel_back_lm";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2569.55, 431.88, 168), (0, 225, 0), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_left_door_blue";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2494.95, 490.22, 239), (0, 225, 0), "trial_truck_door_left", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_right_door_blue";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2567.43, 562.7, 239), (0, 225, 0), "trial_truck_door_right", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_lm_alt_blue";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2648.74, 409.25, 160), (0, 225, 0), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_door_front_right_lm_blue";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2766.05, 348.05, 214.67), (0, 225, 0), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_door_front_left_lm_blue";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2709.49, 291.48, 214.67), (0, 225, 0), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_wheel_front_lm";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2682.69, 318.75, 168), (0, 225, 0), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_wheel_front_lm";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-2739.25, 375.31, 168), (0, 45, 0), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-2508.75, 545.75, 195.5), (0, 238, 0), "trial_waypoint_knife", undefined, "0", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "storage_shelf_beam_wood_plank";
  var0[[var3]](var4, var1, var2, (-230.25, 264.25, 243.5), (0.56, 308, 12.09), "trial_plank_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-900.25, -312.75, 305.75), (0, 199.89, 0), "trial_waypoint_knife", undefined, "9", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (-666, -218, 316.25), (0, 255.12, 0), "trial_waypoint_knife", undefined, "10", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1636.75, -111.5, 126.25), (0, 0, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1512.5, -862.75, 98.75), (0, 45.75, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1512.5, -862.75, 153.75), (0, 45.75, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1547.5, -898.75, 98.75), (0, 45.75, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-577, 89.5, 127), (0, 343, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-254.25, 285, 127), (0, 343, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-254.25, 285, 181.75), (0, 301, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1112.5, -362.25, 114.25), (-4, 111, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1111, -365, 169), (-4, 111, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "military_carepackage_01_uk";
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-1093, -408.5, 111), (-4, 111, 0), "trial_crate_model", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-215, 315, 260.5), (0, 132.47, 0), "trial_waypoint_pistol", undefined, "12", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (696, 142, 308), (0, 199, 0), "trial_waypoint_pistol", undefined, "14", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (1316, 336, 210), (0, 262.99, 0), "trial_waypoint_pistol", undefined, "15", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (1788, 602, 216), (0, 276.99, 0), "trial_waypoint_pistol", undefined, "17", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (1750, 1130, 252), (0, 176.99, 0), "trial_waypoint_pistol", undefined, "18", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-1745.5, 87.5, 183.75), (0, 108.41, 0), "trial_waypoint_pistol", undefined, "4", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-2192, 760, 256.5), (0, 121.8, 0), "trial_waypoint_pistol", undefined, "2", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-1858.5, 297.75, 225), (0, 113.75, 0), "trial_waypoint_pistol", undefined, "3", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-1687.25, -116.25, 259.75), (0, 92.68, 0), "trial_waypoint_pistol", undefined, "5", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-1683.25, -480, 257.25), (0, 130.63, 0), "trial_waypoint_pistol", undefined, "6", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-1412.75, -720.75, 292.25), (0, 176, 0), "trial_waypoint_pistol", undefined, "7", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-1096, -715.25, 289), (0, 235.5, 0), "trial_waypoint_pistol", undefined, "8", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "highway_flag0";
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (2208, 972, 322), (0, 285, 0), "trial_waypoint_pistol", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-558, 193.75, 277.75), (0, 201.91, 0), "trial_waypoint_pistol", undefined, "11", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (130, 82, 256), (0, 185, 0), "trial_waypoint_pistol", undefined, "13", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (2208, 972, 326), (0, 90, 0), "trial_waypoint_pistol", undefined, "19", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-2412.5, 718.25, 203), (0, 198, 0), "trial_waypoint_pistol", undefined, "1", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-2508.75, 545.75, 195.5), (0, 238, 0), "trial_waypoint_pistol", undefined, "0", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-900.25, -312.75, 305.75), (0, 199.89, 0), "trial_waypoint_pistol", undefined, "9", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-666, -218, 316.25), (0, 255.12, 0), "trial_waypoint_pistol", undefined, "10", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var0[[var3]](var4, var1, var2, (-2564.25, 495.75, 243.25), (0, 45, 0), "", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "me_sign_minefield";
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-2391.44, 728.95, 188.97), (0, 260.98, 0), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "offhand_wm_at_mine";
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-2026.95, 613.23, 198.99), undefined, "enemy_mine", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "offhand_wm_at_mine";
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-2415.7, 696.23, 201.49), undefined, "enemy_mine", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "me_sign_minefield";
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-2430.69, 732.2, 188.97), (0, 266.29, 0), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "offhand_wm_at_mine";
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-1673.7, -393.02, 255.99), undefined, "enemy_mine", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "offhand_wm_at_mine";
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (-274.7, 267.48, 237.99), (347.77, 40, -0), "enemy_mine", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "offhand_wm_at_mine";
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (1231.55, 278.98, 175.24), (357.04, 359.11, 2.23), "enemy_mine", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "offhand_wm_at_mine";
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (1788.8, 871.48, 229.74), (0, 0, 0), "enemy_mine", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "offhand_wm_at_mine";
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (1808.8, 1169.73, 249.49), (0, 0, 0), "enemy_mine", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-417.52, 421.13, 124), (0, 0, 0), undefined, undefined, "trial_vfx_gas_linger_lg", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial";
  var0[[var3]](var4, var1, var2, (-981, 162.75, 133), (-90, 235.2, -169.8), undefined, undefined, "trial_vfx_gas_linger", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_knife";
  var0[[var3]](var4, var1, var2, (1352, 684, 190), (0, 168.99, 0), "trial_waypoint_knife", undefined, "16", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.script_gameobjectname = "trial_variant_pistol";
  var0[[var3]](var4, var1, var2, (1352, 684, 190), (0, 168.99, 0), "trial_waypoint_pistol", undefined, "16", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_wheel_front_lm";
  var0[[var3]](var4, var1, var2, (-1612.25, -546.5, 254.5), (20.59, 5.71, -81.66), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_wheel_front_lm";
  var0[[var3]](var4, var1, var2, (-1616.25, -541.25, 246), (24.34, 6.36, -78.4), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_wheel_front_lm";
  var0[[var3]](var4, var1, var2, (-1636.75, -522.25, 256.25), (0, 270, 90), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_wheel_front_lm";
  var0[[var3]](var4, var1, var2, (-1640.78, -556.2, 258.94), (358.16, 272.9, -87.78), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\so_trigger::s();
  var4.is_cs_model = 1;
  var4.model = "veh8_civ_lnd_malfa_wheel_front_lm";
  var0[[var3]](var4, var1, var2, (-1638, -561.25, 246.75), (344.65, 80.94, -73.99), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var0 scripts\engine\utility::ent_flag_set("cs_structs_complete");
}

function createtriggers(var0, var1, var2) {
  var3 = spawnStruct();
  var3.is_cs_trigger = 1;
  var3.angles = (0, 0, 0);
  var3.height = 168;
  var3.origin = (-1805, -2972, -22);
  var3.radius = 3000;
  var3.targetname = "trigger_on_ground";
  var3.script_gameobjectname = "trial";
  var3.script_noteworthy = "trigger_on_ground";
  var0 scripts\cp\so_trigger::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.is_cs_trigger = 1;
  var3.angles = (0.75, 359.99, 1.13);
  var3.height = 168;
  var3.origin = (-2285, 276, -2);
  var3.radius = 2000;
  var3.targetname = "trigger_on_ground";
  var3.script_gameobjectname = "trial";
  var3.script_noteworthy = "trigger_on_ground";
  var0 scripts\cp\so_trigger::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.is_cs_trigger = 1;
  var3.angles = (0, 0, 0);
  var3.height = 168;
  var3.origin = (2287, 1669, -9);
  var3.radius = 1000;
  var3.targetname = "trigger_on_ground";
  var3.script_gameobjectname = "trial";
  var3.script_noteworthy = "trigger_on_ground";
  var0 scripts\cp\so_trigger::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.is_cs_trigger = 1;
  var3.angles = (0.2, 0, 0.2);
  var3.height = 168;
  var3.origin = (835, 148, -24.25);
  var3.radius = 1500;
  var3.targetname = "trigger_on_ground";
  var3.script_gameobjectname = "trial";
  var3.script_noteworthy = "trigger_on_ground";
  var0 scripts\cp\so_trigger::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.is_cs_trigger = 1;
  var3.angles = (0, 0, 0);
  var3.height = 168;
  var3.origin = (2567, -59, -9);
  var3.radius = 1000;
  var3.targetname = "trigger_on_ground";
  var3.script_gameobjectname = "trial";
  var3.script_noteworthy = "trigger_on_ground";
  var0 scripts\cp\so_trigger::strike_additem(var3, var1, var2);
  var0 scripts\engine\utility::ent_flag_set("cs_triggers_complete");
}