/**************************************************************
 * Decompiled by ATE47 and Edited by SyndiShanX
 * Script: scripts\cp\maps\cp_donetsk\cp_donetsk_intel_cs.gsc
**************************************************************/

function main(var0, var1) {
  level endon("game_ended");

  if(scripts\engine\utility::flag_exist("cp_donetsk_intel_cs")) {
    return;
  }

  scripts\engine\utility::flag_init("cp_donetsk_intel_cs");
  var2 = spawnStruct();
  thread cs_return_and_wait_for_flag(level, var0, var1, var2);

  if(!scripts\cp\cp_create_script_utility::cs_is_starttime()) {
    scripts\cp\cp_create_script_utility::endcreatescript(var2);
    return;
  }
}

function cs_return_and_wait_for_flag(var0, var1, var2, var3) {
  scripts\cp\cp_create_script_utility::wait_for_cs_flag(var3);

  if(!isDefined(var1)) {
    var1 = "stk";
  }

  var2 scripts\cp\cp_create_script_utility::strike_setup_arrays(var1, "cp_donetsk_intel_cs");
  scripts\cp\cp_create_script_utility::cs_init_flags(var2);
  thread createstructs(level, var2, var1);
  thread createtriggers(level, var2, var1);
  thread createmodels(level, var2, var1);

  if(istrue(var0)) {
    level thread scripts\cp\cp_create_script_utility::wait_for_flags(var2, "cp_donetsk_intel_cs");
    return;
  }

  scripts\cp\cp_create_script_utility::wait_for_flags(var2, "cp_donetsk_intel_cs");
}

function createstructs(var0, var1, var2) {
  var3 = &scripts\cp\cp_create_script_utility::strike_additem;
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (21277.2, -7833.07, 3000), undefined, "ml_p2_get_heli", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (20340.7, -9464.04, 3000), undefined, "ml_p1_intel", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (19341.1, -1098.29, 3000), undefined, "ml_p2_secure_loc", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (17643.1, -9167.79, 3000), undefined, "ml_p3_intel", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (25864.6, -16533.3, 3000), undefined, "vault_assault", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (-4188.67, 32957.6, 3000), undefined, "obj_caches", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (22958.3, 29759.2, 3000), undefined, "obj_tug_of_war", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (29126, 34614.7, 3000), undefined, "convoy4_securearea", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (32632.9, 39599.9, 3000), undefined, "convoy4_secure_tower", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (32045, 5682.58, 2553.84), undefined, "obj_overwatch", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (17509.7, 8841.39, 2661.47), undefined, "obj_tmtyl", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (17958.2, 8827.89, 2661.47), undefined, "obj_tmtyl_0", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (-25844, 7681.95, 2680), undefined, "morales_1", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (-16067, 4400.76, 2615.8), undefined, "obj_payload", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (-13241.7, 3464.85, 2674.49), undefined, "obj_armsrace", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (-21953.6, 13510.9, 2682.83), undefined, "plant_jammers", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var4.name = "airport";
  var0[[var3]](var4, var1, var2, (-22306.6, 19300.4, 2682.83), undefined, "plant_jammers", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (-22295.1, 21589.4, 2656.5), undefined, "infil_plane", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (-24731.3, -11596.5, 3180), undefined, "land_at_lz", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (4811, 50400, 3759), undefined, "ba_mnu", undefined, "respawn_point", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var4.script_linkname = "1";
  var0[[var3]](var4, var1, var2, (25124.5, -16899.5, 2340), undefined, "ks_heli_goal", undefined, "ml_p1_heli_goal", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (17953.5, -20070, 2931.5), undefined, "ks_heli_entrance", undefined, "ml_p1_heli_entrance", "1", undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var4.script_linkname = "2";
  var0[[var3]](var4, var1, var2, (26438, -12504.5, 2549.5), undefined, "ks_heli_goal", undefined, "ml_p2_heli_goal", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (21472, -17582.5, 3141), undefined, "ks_heli_entrance", undefined, "ml_p2_heli_entrance", "2", undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var4.script_linkname = "3";
  var0[[var3]](var4, var1, var2, (22213.5, -2984, 1800), undefined, "ks_heli_goal", undefined, "ml_p2_2_heli_goal", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (27759.5, -7310.5, 2391.5), undefined, "ks_heli_entrance", undefined, "ml_p2_2_heli_entrance", "3", undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var4.script_linkname = "4";
  var0[[var3]](var4, var1, var2, (15762, -7346, 1942), undefined, "ks_heli_goal", undefined, "ml_p3_heli_goal", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var4 = scripts\cp\cp_create_script_utility::s();
  var0[[var3]](var4, var1, var2, (17788, -12988, 2533.5), undefined, "ks_heli_entrance", undefined, "ml_p3_heli_entrance", "4", undefined, undefined, undefined, undefined, undefined, undefined);
  var0 scripts\engine\utility::ent_flag_set("cs_structs_complete");
}

function createtriggers(var0, var1, var2) {
  var0 scripts\engine\utility::ent_flag_set("cs_triggers_complete");
}

function createmodels(var0, var1, var2) {
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.script_noteworthy = "launderer2_2";
  var3.angles = (0, 210, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (29337, -16083.5, -287.5);
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.script_noteworthy = "launderer_4";
  var3.classname = "script_model";
  var3.angles = (0, 210, 0);
  var3.model = "ee_book_office_folder_02";
  var3.origin = (21426.5, -3877.5, -360);
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 14.3, 0);
  var3.model = "ee_book_office_folder_02";
  var3.origin = (20481.5, 3827.5, 236.5);
  var3.script_noteworthy = "landlord_4";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.angles = (0, 122, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (14422, 8804.5, -282);
  var3.script_noteworthy = "landlord_1";
  var3.targetname = "intel_piece";
  var3.classname = "script_model";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.targetname = "intel_piece";
  var3.classname = "script_model";
  var3.angles = (0, 112, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (2426.15, 52242.9, 1586.06);
  var3.script_noteworthy = "landlord2_2";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 154.89, 0);
  var3.model = "offhand_wm_cellphone_old";
  var3.origin = (34652.5, 5607.44, -773.7);
  var3.script_noteworthy = "landlord_5";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 186, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (33556, -3031.71, -498.99);
  var3.script_noteworthy = "landlord_2";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.script_noteworthy = "launderer2_5";
  var3.angles = (0, 284, 0);
  var3.model = "ee_book_office_folder_02";
  var3.origin = (23132.5, -18199, -43.5);
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.script_noteworthy = "launderer2_1";
  var3.angles = (0, 210, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (24993, -14347.5, -155.5);
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.script_noteworthy = "launderer_5";
  var3.angles = (0, 210, 0);
  var3.model = "offhand_wm_cellphone_old";
  var3.origin = (18983, -22266.5, 192.5);
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.script_noteworthy = "launderer2_4";
  var3.angles = (0, 210, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (21626, -15927.5, 1913);
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 122, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (23116.8, -5204.89, 1087);
  var3.script_noteworthy = "landlord_3";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.angles = (0, 80, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (2067.27, 46580.1, 1452.5);
  var3.script_noteworthy = "landlord2_1";
  var3.targetname = "intel_piece";
  var3.classname = "script_model";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 80, 0);
  var3.model = "ee_book_office_folder_02";
  var3.origin = (-279.82, 47202.1, 3397.11);
  var3.script_noteworthy = "landlord2_4";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 140, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (10687.1, 56118.8, 1079);
  var3.script_noteworthy = "landlord2_3";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 80, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (20248.2, 44281.8, 964.75);
  var3.script_noteworthy = "landlord2_5";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 122, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (-26398, 10579.5, -274.5);
  var3.script_noteworthy = "dealer_1";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 95, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (-8243.42, 5850.69, -308);
  var3.script_noteworthy = "dealer_2";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 122, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (-11115.5, -533.5, -131.5);
  var3.script_noteworthy = "dealer_3";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (350.65, 105.15, -1.91);
  var3.model = "offhand_wm_cellphone_old";
  var3.origin = (-18273.3, -2824.49, -247.73);
  var3.script_noteworthy = "dealer_5";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 234, 0);
  var3.model = "ee_book_office_folder_02";
  var3.origin = (-12641, 7465.62, 170);
  var3.script_noteworthy = "dealer_4";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 122, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (-27952.8, -17928.2, -36.5);
  var3.script_noteworthy = "dealer2_3";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 122, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (-21343.3, 17807.9, -284);
  var3.script_noteworthy = "dealer2_1";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 122, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (-26076.5, 18834.9, -635.5);
  var3.script_noteworthy = "dealer2_2";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 332.89, 0);
  var3.model = "ee_book_office_folder_02";
  var3.origin = (-22512, 27651.5, 1164.5);
  var3.script_noteworthy = "dealer2_4";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (22.75, 0.29, 52.08);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (-25682.9, 15124.7, -310.5);
  var3.script_noteworthy = "dealer2_5";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 154.89, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (3363.07, 28048.5, 175.12);
  var3.script_noteworthy = "smuggler_5";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 106.89, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (5086.62, 35061.5, 2308.97);
  var3.script_noteworthy = "smuggler_1";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 154.89, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (24753.8, 21919.6, 1787.95);
  var3.script_noteworthy = "smuggler_3";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 154.89, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (13941.4, 33481.2, 1656.5);
  var3.script_noteworthy = "smuggler_2";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 154.89, 0);
  var3.model = "ee_book_office_folder_02";
  var3.origin = (34648.4, 26664.8, 623.75);
  var3.script_noteworthy = "smuggler_4";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 154.89, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (31733.7, 33192.3, 927);
  var3.script_noteworthy = "smuggler2_1";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 154.89, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (29382.3, 32694.5, 822.5);
  var3.script_noteworthy = "smuggler2_3";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 154.89, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (37047.4, 45951, 488);
  var3.script_noteworthy = "landlord_5";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 154.89, 0);
  var3.model = "offhand_wm_cellphone_old";
  var3.origin = (35245.7, 44809.5, 1949.5);
  var3.script_noteworthy = "smuggler2_4";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 154.89, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (31424.8, 40400.5, 1295.67);
  var3.script_noteworthy = "smuggler2_2";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.angles = (0, 154.89, 0);
  var3.model = "ee_book_office_folder_02";
  var3.origin = (37473.3, 48644, 1045.5);
  var3.script_noteworthy = "smuggler2_5";
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.script_noteworthy = "launderer_1";
  var3.angles = (0, 120, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (19939.2, -17584.6, -62.6);
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.script_noteworthy = "launderer_2";
  var3.angles = (0, 298, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (20214.5, -7941.22, -367.5);
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.classname = "script_model";
  var3.script_noteworthy = "launderer_3";
  var3.angles = (0, 120, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (30389.4, -8722.58, -415.5);
  var3.targetname = "intel_piece";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var3 = spawnStruct();
  var3.script_noteworthy = "launderer2_3";
  var3.angles = (0, 210, 0);
  var3.model = "electronics_usb_thumb_drive";
  var3.origin = (23070.5, -20512.5, 212);
  var3.targetname = "intel_piece";
  var3.classname = "script_model";
  var0 scripts\cp\cp_create_script_utility::strike_additem(var3, var1, var2);
  var0 scripts\engine\utility::ent_flag_set("cs_models_complete");
}