/*********************************************
 * Decompiled by Bog and Edited by SyndiShanX
 * Script: 1193.gsc
*********************************************/

func_00F9() {
  level._effect["gib_fire_medium_by_radar"] = loadfx("vfx/map/mp_gibraltar/gib_fire_medium_by_radar");
  level._effect["gib_vista_clouds"] = loadfx("vfx/map/mp_gibraltar/gib_vista_clouds");
  level._effect["gib_horizon_fog"] = loadfx("vfx/map/mp_gibraltar/gib_horizon_fog");
  level._effect["gib_fire_small_1"] = loadfx("vfx/map/mp_gibraltar/gib_fire_small_1");
  level._effect["gib_boat_foam_1"] = loadfx("vfx/map/mp_gibraltar/gib_boat_foam_1");
  level._effect["gib_smoke_boat_black_locked"] = loadfx("vfx/map/mp_gibraltar/gib_smoke_boat_black_locked");
  level._effect["mp_smoke_trail__thick"] = loadfx("vfx/map/mp_gibraltar/mp_smoke_trail__thick");
  level._effect["gib_fire_smoke_distance_boats"] = loadfx("vfx/map/mp_gibraltar/gib_fire_smoke_distance_boats");
  level._effect["gib_fire_distance_boats"] = loadfx("vfx/map/mp_gibraltar/gib_fire_distance_boats");
  level._effect["gib_light_shafts_cave_far"] = loadfx("vfx/map/mp_gibraltar/gib_light_shafts_cave_far");
  level._effect["gib_fire_distance"] = loadfx("vfx/map/mp_gibraltar/gib_fire_distance");
  level._effect["gib_smoke_column_white_vol_1"] = loadfx("vfx/map/mp_gibraltar/gib_smoke_column_white_vol_1");
  level._effect["gib_bird_seagulls_flying_runner"] = loadfx("vfx/map/mp_gibraltar/gib_bird_seagulls_flying_runner");
  level._effect["mp_fog_whisps_d"] = loadfx("vfx/map/mp_gibraltar/mp_fog_whisps_d");
  level._effect["mp_fog_whisps_c"] = loadfx("vfx/map/mp_gibraltar/mp_fog_whisps_c");
  level._effect["gib_smoke_column_boat_1"] = loadfx("vfx/map/mp_gibraltar/gib_smoke_column_boat_1");
  level._effect["gib_light_shafts_2"] = loadfx("vfx/map/mp_gibraltar/gib_light_shafts_2");
  level._effect["gib_motes_1"] = loadfx("vfx/map/mp_gibraltar/gib_motes_1");
  level._effect["gib_light_shafts_1"] = loadfx("vfx/map/mp_gibraltar/gib_light_shafts_1");
  level._effect["water_dripping_contstant"] = loadfx("vfx/map/mp_gibraltar/water_dripping_contstant");
  level._effect["smoke_heavy_window_fire"] = loadfx("vfx/map/mp_gibraltar/smoke_heavy_window_fire");
  level._effect["water_splash_no_rings"] = loadfx("vfx/map/mp_gibraltar/water_splash_no_rings");
  level._effect["tunnel_dripping_water_small_runner"] = loadfx("vfx/map/mp_gibraltar/tunnel_dripping_water_small_runner");
  level._effect["steam_gentle_large_trail"] = loadfx("vfx/map/mp_gibraltar/steam_gentle_large_trail");
  level._effect["ambient_interior_motes"] = loadfx("vfx/map/mp_gibraltar/ambient_interior_motes");
  level._effect["mp_smoke_trail__thin"] = loadfx("vfx/map/mp_gibraltar/mp_smoke_trail__thin");
  level._effect["mp_fog_whisps_b"] = loadfx("vfx/map/mp_gibraltar/mp_fog_whisps_b");
  level._effect["mp_fog_whisps_a"] = loadfx("vfx/map/mp_gibraltar/mp_fog_whisps_a");
  level._effect["water_splash_rings"] = loadfx("vfx/map/mp_gibraltar/water_splash_rings");
  level._effect["falling_water_drip_ripple_looping"] = loadfx("vfx/map/mp_gibraltar/falling_water_drip_ripple_looping");
  level._effect["steam_gentle_large"] = loadfx("vfx/map/mp_gibraltar/steam_gentle_large");
  level._effect["steam_leak_medium"] = loadfx("vfx/map/mp_gibraltar/steam_leak_medium");
  level._effect["ambient_leaves_falling_leaves_runner"] = loadfx("vfx/map/mp_gibraltar/ambient_leaves_falling_leaves_runner");
  level._effect["black_bits_large"] = loadfx("vfx/map/mp_gibraltar/black_bits_large");
  level._effect["smoke_heavy_window"] = loadfx("vfx/map/mp_gibraltar/smoke_heavy_window");
  level._effect["mp_fog_rolling_bay"] = loadfx("vfx/map/mp_gibraltar/mp_fog_rolling_bay");
  level._effect["smoke_heavy_column_shadow_wind"] = loadfx("vfx/map/mp_gibraltar/smoke_heavy_column_shadow_wind");
  level._effect["smoke_heavy_column_wind"] = loadfx("vfx/map/mp_gibraltar/smoke_heavy_column_wind");
  level._effect["electrical_sparks_burst_runner"] = loadfx("vfx/map/mp_gibraltar/electrical_sparks_burst_runner");
  level._effect["water_leak_pipe_with_steam"] = loadfx("vfx/map/mp_gibraltar/water_leak_pipe_with_steam");
  level._effect["bits_air_pedals_yellow_runner"] = loadfx("vfx/map/mp_gibraltar/bits_air_pedals_yellow_runner");
  level._effect["bits_air_pedals_runner"] = loadfx("vfx/map/mp_gibraltar/bits_air_pedals_runner");
  level._effect["bits_air_pedals_small"] = loadfx("vfx/map/mp_gibraltar/bits_air_pedals_small");
  level._effect["light_cone_simple_cave"] = loadfx("vfx/map/mp_gibraltar/light_cone_simple_cave");
  level._effect["dust_ambient_interior_hall_beige"] = loadfx("vfx/map/mp_gibraltar/dust_ambient_interior_hall_beige");
  level._effect["dust_ambient_interior_hall"] = loadfx("vfx/map/mp_gibraltar/dust_ambient_interior_hall");
  level._effect["bits_air_medium"] = loadfx("vfx/map/mp_gibraltar/bits_air_medium");
  level._effect["light_cone_simple_gentle"] = loadfx("vfx/map/mp_gibraltar/light_cone_simple_gentle");
  level._effect["smoke_lite_column_wind"] = loadfx("vfx/map/mp_gibraltar/smoke_lite_column_wind");
  level._effect["dust_falling_debris_2_runner"] = loadfx("vfx/map/mp_gibraltar/dust_falling_debris_2_runner");
  level._effect["dust_falling_debris_runner"] = loadfx("vfx/map/mp_gibraltar/dust_falling_debris_runner");
  level._effect["pebbles_falling_velocity_runner"] = loadfx("vfx/map/mp_gibraltar/pebbles_falling_velocity_runner");
  level._effect["steam_sm_vent_slow_wind"] = loadfx("vfx/map/mp_gibraltar/steam_sm_vent_slow_wind");
  level._effect["dust_ground_small"] = loadfx("vfx/map/mp_gibraltar/dust_ground_small");
  level._effect["steam_leak_small"] = loadfx("vfx/map/mp_gibraltar/steam_leak_small");
  level._effect["greece_ambient_foliage_runner_dense"] = loadfx("vfx/map/greece/greece_ambient_foliage_runner_dense");
  level._effect["ambient_foliage_runner"] = loadfx("vfx/wind/ambient_foliage_runner");
  level._effect["mp_fog_rolling_peak"] = loadfx("vfx/map/mp_gibraltar/mp_fog_rolling_peak");
  level._effect["tunnel_dripping_water_runner"] = loadfx("vfx/map/mp_gibraltar/tunnel_dripping_water_runner");
  level._effect["ambient_maple_falling_leaves_runner"] = loadfx("vfx/wind/ambient_maple_falling_leaves_runner");
  level._effect["ambient_maple_falling_leaves_c"] = loadfx("vfx/wind/ambient_maple_falling_leaves_c");
  level._effect["ambient_maple_falling_leaves_b"] = loadfx("vfx/wind/ambient_maple_falling_leaves_b");
  level._effect["ambient_maple_falling_leaves"] = loadfx("vfx/wind/ambient_maple_falling_leaves");
  level._effect["gb_cloud_rolling_cliffside_up"] = loadfx("vfx/map/gibraltar/gb_cloud_rolling_cliffside_up");
  level._effect["vf_wind_mp_gibraltar_a"] = loadfx("vfx/vectorfield/vf_wind_mp_gibraltar_a");
  level._effect["test_effect"] = loadfx("vfx/test/test_fx");
  level._effect["fx_sunflare_gibraltar_02"] = loadfx("vfx/lensflare/fx_sunflare_gibraltar_02");
  level._effect["dday_flare_light_bulb"] = loadfx("vfx/lights/mp_d_day/dday_flare_light_bulb");
  level._effect["cloud_shadows"] = loadfx("vfx/cloud/cloud_shadows_lrg");
}