/**************************************
 * Decompiled and Edited by SyndiShanX
 * Script: 3132.gsc
**************************************/

_id_2371() {
  if(scripts\asm\asm::_id_232E("c6_worker")) {
    return;
  }
  scripts\asm\asm::_id_230B("c6_worker", "init");
  scripts\asm\asm::_id_2374("init", _id_0C3B::_id_13DC4, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("poweroff_cointoss", undefined, _id_0C3B::_id_9F06, undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\shared\utility::_id_12668, undefined);
  scripts\asm\asm::_id_2374("poweroff_cointoss", scripts\asm\shared\utility::_id_2B58, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("poweroff_1", undefined, ::_id_1240E, undefined);
  scripts\asm\asm::_id_2375("poweroff_2", undefined, scripts\asm\shared\utility::_id_12668, undefined);
  scripts\asm\asm::_id_2374("stand_idle", _id_0F3D::_id_B050, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, "pain_stand", undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", "angle deltas", undefined);
  scripts\asm\asm::_id_2375("poweroff_cointoss", undefined, _id_0C3B::_id_9F06, undefined);
  scripts\asm\asm::_id_2375("melee_decide_winner", undefined, scripts\asm\asm_bb::bb_meleerequested, undefined);
  scripts\asm\asm::_id_2375("stand_turn", undefined, _id_0C3B::_id_340F, undefined);
  scripts\asm\asm::_id_2375("move_requested", undefined, scripts\asm\asm::_id_BCE7, undefined);
  scripts\asm\asm::_id_2374("move_loop", _id_0C3B::_id_3415, undefined, undefined, undefined, undefined, _id_0C3B::_id_3407, undefined, undefined, undefined, undefined, undefined, "pain_move", undefined, "death_generic", undefined, undefined, undefined, undefined, "face motion", "normal", undefined);
  scripts\asm\asm::_id_2375("melee_decide_winner", undefined, scripts\asm\asm_bb::bb_meleerequested, undefined);
  scripts\asm\asm::_id_2375("poweroff_cointoss", undefined, _id_0C3B::_id_9F06, undefined);
  scripts\asm\asm::_id_2375("move_arrival", undefined, _id_0C3B::_id_341C, undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\asm::_id_C17F, undefined);
  scripts\asm\asm::_id_2374("Knobs", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2374("death_generic", scripts\asm\shared\utility::_id_2B58, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("death_shocked", undefined, _id_0C60::_id_10052, undefined);
  scripts\asm\asm::_id_2375("shield_bash", undefined, _id_0C60::_id_10051, undefined);
  scripts\asm\asm::_id_2375("death_knife_upgrade", undefined, _id_0C60::_id_FFF0, undefined);
  scripts\asm\asm::_id_2375("death_explosive", undefined, _id_0C60::_id_10045, undefined);
  scripts\asm\asm::_id_2375("death_default", undefined, scripts\asm\shared\utility::_id_12668, undefined);
  scripts\asm\asm::_id_2374("melee_attack", _id_0F42::_id_D4D7, undefined, undefined, undefined, undefined, _id_0C3B::_id_3406, undefined, undefined, undefined, undefined, undefined, "pain_stand", undefined, "death_generic", undefined, undefined, undefined, "melee_attack", "face enemy", "zonly_physics", undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2374("dismember", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("dismember_left_leg", undefined, scripts\asm\asm_bb::bb_ispartdismembered, "left_leg");
  scripts\asm\asm::_id_2375("dismember_right_leg", undefined, scripts\asm\asm_bb::bb_ispartdismembered, "right_leg");
  scripts\asm\asm::_id_2375("dismember_left_arm", undefined, scripts\asm\asm_bb::bb_ispartdismembered, "left_arm");
  scripts\asm\asm::_id_2375("dismember_right_arm", undefined, scripts\asm\asm_bb::bb_ispartdismembered, "right_arm");
  scripts\asm\asm::_id_2374("dismember_left_arm", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, "pain_stand", undefined, "death_generic", undefined, undefined, undefined, "dismember", undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2374("dismember_right_arm", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, "pain_stand", undefined, "death_generic", undefined, undefined, undefined, "dismember", undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2374("dismember_left_leg", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, "pain_stand", undefined, "death_crawl", undefined, undefined, undefined, "dismember", undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("crawl_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2374("dismember_right_leg", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, "pain_stand", undefined, "death_crawl", undefined, undefined, undefined, "dismember", undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("crawl_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2374("crawl_idle", _id_0F3D::_id_B050, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, "pain_crawl", undefined, "death_crawl", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("crawlmelee_move", undefined, scripts\asm\asm::_id_BCE7, undefined);
  scripts\asm\asm::_id_2374("death_crawl", _id_0C60::_id_CF0E, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2374("AnimScripted", _id_0F3D::_id_1FCB, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, ::_id_11B75, undefined);
  scripts\asm\asm::_id_2374("traverse_external", _id_0C6B::_id_D560, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("traverse_complete", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("crawl_idle", undefined, _id_0A26::_id_337F, undefined);
  scripts\asm\asm::_id_2375("move_loop", undefined, scripts\asm\asm::_id_BCE7, undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\shared\utility::_id_12668, undefined);
  scripts\asm\asm::_id_2374("window_over_quick", _id_0C6B::_id_D566, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("window_divethrough_36", _id_0C6B::_id_D566, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("wall_hop", _id_0C6B::_id_D55D, 39.875, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("jumpdown_rail_88", _id_0C6B::_id_D566, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("jumpdown_56", _id_0C6B::_id_D566, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("jumpdown_40", _id_0C6B::_id_D566, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("double_jump_temp", _id_0C6B::_id_D55E, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpdown_high", _id_0C3B::_id_126D6, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpdown_med", _id_0C3B::_id_126D6, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpdown_rail_left", _id_0C3B::_id_126D6, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpdown_rail", _id_0C3B::_id_126D6, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpdown_left", _id_0C3B::_id_126D6, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpdown_right", _id_0C3B::_id_126D6, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpup_rail_right", _id_0C3B::_id_126D6, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpup_rail_left", _id_0C3B::_id_126D6, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpdown_rail_right", _id_0C3B::_id_126D6, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpup_rail", _id_0C3B::_id_126D6, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("poweroff_1", _id_0C3B::_id_3412, undefined, undefined, _id_0C3B::_id_3419, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, "pain_stand", undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", "zonly_physics", undefined);
  scripts\asm\asm::_id_2375("poweroff_complete_1", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2374("poweroff_2", _id_0C3B::_id_3412, undefined, undefined, _id_0C3B::_id_3419, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, "pain_stand", undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", "zonly_physics", undefined);
  scripts\asm\asm::_id_2375("poweroff_complete_2", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2374("powerup_1", _id_0C3B::_id_3413, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, "pain_stand", undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", "zonly_physics", undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2374("c6worker_climbup_96_double", _id_0C6B::_id_126CE, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("powerup_2", _id_0C3B::_id_3413, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, "pain_stand", undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", "zonly_physics", undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2374("poweroff_complete_1", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("powerup_1", undefined, _id_0C3B::_id_C17D, undefined);
  scripts\asm\asm::_id_2374("poweroff_complete_2", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("powerup_2", undefined, _id_0C3B::_id_C17D, undefined);
  scripts\asm\asm::_id_2374("c6worker_climbup_96_single", _id_0C6B::_id_126CE, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpup_tiered_right", _id_0C6B::_id_126CE, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpup_tiered_left", _id_0C6B::_id_126CE, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpover_40", _id_0C6B::_id_126CE, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpover_40_short", _id_0C6B::_id_126CE, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpover_48", _id_0C6B::_id_126CE, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpover_48_short", _id_0C6B::_id_126CE, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("c6worker_jumpacross_rail_to_rail", _id_0C6B::_id_126CE, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", undefined, undefined);
  scripts\asm\asm::_id_2375("traverse_complete", undefined, scripts\asm\asm::_id_68B0, "traverse_end");
  scripts\asm\asm::_id_2374("stand_turn", _id_0C3B::_id_3418, undefined, undefined, undefined, undefined, _id_0C3B::_id_3408, undefined, undefined, undefined, undefined, undefined, "pain_stand", undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", "zonly_physics", undefined);
  scripts\asm\asm::_id_2375("stand_turn_complete", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2374("move_exit", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, "pain_move", undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", "zonly_physics", undefined);
  scripts\asm\asm::_id_2375("move_loop", undefined, scripts\asm\asm::_id_68B0, "code_move");
  scripts\asm\asm::_id_2374("move_arrival", _id_0C3B::_id_3414, undefined, undefined, undefined, undefined, _id_0C3B::_id_3405, undefined, undefined, undefined, undefined, undefined, "pain_move", undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", "zonly_physics", undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2374("stand_turn_complete", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("move_exit", undefined, scripts\asm\asm::_id_BCE7, undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\shared\utility::_id_12668, undefined);
  scripts\asm\asm::_id_2374("move_requested", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("move_exit", undefined, _id_0C3B::_id_341A, undefined);
  scripts\asm\asm::_id_2375("move_loop", undefined, scripts\asm\shared\utility::_id_12668, undefined);
  scripts\asm\asm::_id_2374("death_default", _id_0C60::_id_CF0E, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2374("shield_bash", _id_0A26::_id_33AC, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2374("death_shocked", _id_0C60::_id_CF0E, undefined, undefined, undefined, undefined, _id_0C60::_id_3EF6, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2374("pain_stand", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("pain_shock", undefined, _id_0A1E::_id_9F4C, undefined);
  scripts\asm\asm::_id_2374("pain_move", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("pain_shock", undefined, _id_0A1E::_id_9F4C, undefined);
  scripts\asm\asm::_id_2374("pain_shock", _id_0C3B::_id_3416, undefined, _id_0C2F::_id_33AD, _id_0C3B::_id_3417, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\asm::_id_68B0, "stop_loop_pain");
  scripts\asm\asm::_id_2374("pain_stand_default", _id_0C3B::_id_3411, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, "pain", undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, "face current", undefined, undefined);
  scripts\asm\asm::_id_2374("pain_move_default", _id_0C3B::_id_3411, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, "pain", undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, "face motion", "zonly_physics", undefined);
  scripts\asm\asm::_id_2374("death_explosive", _id_0C60::_id_CF0E, undefined, undefined, undefined, undefined, _id_0C60::_id_3ED8, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2374("death_antigrav_grenade", scripts\asm\shared\utility::_id_2B58, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("death_antigrav_grenade_default", undefined, scripts\asm\shared\utility::_id_12668, undefined);
  scripts\asm\asm::_id_2374("death_antigrav_grenade_default", _id_0C60::_id_CF11, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2374("antigrav_rise", _id_0F41::_id_CEE2, undefined, undefined, undefined, undefined, _id_0F41::_id_3EB1, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_antigrav_grenade", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("antigrav_float_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2375("pick_fall", undefined, _id_0F41::_id_2012, undefined);
  scripts\asm\asm::_id_2374("antigrav_float_idle", _id_0F41::_id_CEE0, undefined, undefined, undefined, undefined, _id_0F41::_id_3EB0, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_antigrav_grenade", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("pick_fall", undefined, _id_0F41::_id_2012, undefined);
  scripts\asm\asm::_id_2374("antigrav_fall", _id_0F41::_id_CEDC, undefined, undefined, _id_0F41::_id_3391, undefined, _id_0F41::_id_3EAD, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_antigrav_grenade", undefined, undefined, undefined, undefined, "face current", "gravity", undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2375("antigrav_rise", undefined, _id_0F41::_id_197C, undefined);
  scripts\asm\asm::_id_2374("antigrav_fall_to_crawl", _id_0F41::_id_CEDC, undefined, undefined, _id_0F41::_id_3391, undefined, _id_0F41::_id_3EAD, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_antigrav_grenade", undefined, undefined, undefined, undefined, "face current", "gravity", undefined);
  scripts\asm\asm::_id_2375("crawl_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2375("antigrav_rise", undefined, _id_0F41::_id_197C, undefined);
  scripts\asm\asm::_id_2374("pick_fall", scripts\asm\shared\utility::_id_2B58, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_generic", undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("antigrav_fall_to_crawl", undefined, _id_0A26::_id_337F, undefined);
  scripts\asm\asm::_id_2375("antigrav_fall", undefined, scripts\asm\shared\utility::_id_12668, undefined);
  scripts\asm\asm::_id_2374("death_knife_upgrade", _id_0A26::_id_3361, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2374("melee_c6_longchoke_lose", _id_0F42::_id_D4D1, undefined, undefined, _id_0F42::_id_D4D3, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_melee_ragdoll_delayed", undefined, undefined, undefined, "melee_attack", "face current", "zonly_physics", undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2375("stand_idle", undefined, _id_0C64::melee_shouldabort, undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, _id_0C3B::_id_9F06, undefined);
  scripts\asm\asm::_id_2374("melee_decider", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("melee_randomizer", undefined, scripts\asm\shared\utility::randomizepassthroughchildren, undefined);
  scripts\asm\asm::_id_2375("melee_attack", undefined, scripts\asm\shared\utility::_id_12668, undefined);
  scripts\asm\asm::_id_2374("melee_decide_winner", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("melee_decider", undefined, _id_0C30::_id_3386, undefined);
  scripts\asm\asm::_id_2374("death_melee_ragdoll_delayed", _id_0C60::_id_CF0F, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, "death", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2374("melee_c6_pound_lose", _id_0F42::_id_D4D1, undefined, undefined, _id_0F42::_id_D4D3, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_melee_ragdoll_delayed", undefined, undefined, undefined, "melee_attack", "face current", "zonly_physics", undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2375("stand_idle", undefined, _id_0C64::melee_shouldabort, undefined);
  scripts\asm\asm::_id_2375("stand_idle", undefined, _id_0C3B::_id_9F06, undefined);
  scripts\asm\asm::_id_2374("melee_randomizer", scripts\asm\shared\utility::_id_2B58, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, 1);
  scripts\asm\asm::_id_2375("melee_c6_longchoke_lose", 0.16, _id_0C3B::_id_340A, 0);
  scripts\asm\asm::_id_2375("melee_c6_pound_lose", undefined, _id_0C3B::_id_340A, 0);
  scripts\asm\asm::_id_2374("crawlmelee_turn", _id_0C65::_id_D514, undefined, undefined, undefined, undefined, _id_0C65::_id_3EF5, undefined, undefined, "prone", undefined, undefined, "pain_crawl", undefined, "death_crawl_moving", undefined, undefined, undefined, undefined, "face enemy or motion", "zonly_physics", undefined);
  scripts\asm\asm::_id_2375("crawlmelee_move", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2374("crawlmelee_move", _id_0F3D::_id_D4DD, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, "prone", undefined, undefined, "pain_crawl", undefined, "death_crawl_moving", undefined, undefined, undefined, undefined, "face motion", "normal", undefined);
  scripts\asm\asm::_id_2375("crawl_idle", undefined, scripts\asm\asm::_id_C17F, undefined);
  scripts\asm\asm::_id_2375("crawlmelee_turn", undefined, _id_0C65::_id_FFF8, ["crawlmelee_turn", 1]);
  scripts\asm\asm::_id_2374("death_crawl_moving", _id_0C60::_id_CF0E, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2374("pain_crawl", _id_0F3D::_id_CEA8, undefined, undefined, undefined, undefined, _id_0F3D::_id_3E96, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "death_crawl", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  scripts\asm\asm::_id_2375("crawl_idle", undefined, scripts\asm\asm::_id_68B0, "end");
  scripts\asm\asm::_id_2327();
}

_id_1240E(var_0, var_1, var_2, var_3) {
  return randomint(100) < 80;
}

_id_11B75(var_0, var_1, var_2, var_3) {
  return !scripts\asm\asm_bb::bb_isanimScripted();
}