/*****************************************************
 * Decompiled and Edited by SyndiShanX
 * Script: maps\sniper_anim.gsc
*****************************************************/

#include maps\_utility;
#include maps\_anim;
#include common_scripts\utility;
#using_animtree("generic_human");

main() {
  level thread addNotetrack_customFunction("hero", "bash", ::hero_opendoor_3, "door_open3");
  level thread addNotetrack_customFunction("gunner", "fire", ::gun_flash, "gun_dudes");
  level thread addNotetrack_customFunction("gunner", "fire", ::gunner_fired_notify, "gun_dudes");
  level thread addNotetrack_customFunction("gunner", "fire", ::shot_effects, "gun_dudes");
  level thread addNotetrack_customFunction("ftn_walker_cross", "fire", ::gun_flash, "walk");
  level thread addNotetrack_customFunction("sniperL_shoot", "sniper_fire", ::notify_sniperfire, "shoot_left_hi");
  level thread addNotetrack_customFunction("sniperL_shoot", "sniper_fire", ::notify_sniperfire, "shoot_left_low");
  level thread addNotetrack_customFunction("sniperL_shoot", "sniper_fire", ::notify_sniperfire, "shoot_pass");
  level thread addNotetrack_customFunction("sniperR_shoot", "sniper_fire", ::notify_sniperfire, "shoot_right_low");
  level thread addNotetrack_customFunction("sniperR_shoot", "sniper_fire", ::notify_sniperfire, "shoot_right_hi");
  level thread addNotetrack_customFunction("sniperR_shoot", "sniper_fire", ::notify_sniperfire, "shoot_pass");
  level thread addNotetrack_customFunction("allies", "grenade_throw", ::molotov_throw, "molotov_toss");
  level thread addNotetrack_customFunction("horchguy2", "chair", ::horchguy2_chairanim, "intro");
  level thread addNotetrack_customFunction("facecrow", "peck_player", ::crow_rumble_pecks, "loop");
  level thread addNotetrack_customFunction("crow1_tree", "feathers", ::play_feather_fx, "outtro");
  level thread addNotetrack_customFunction("crow2_tree", "feathers", ::play_feather_fx, "outtro");
  level thread addNotetrack_customFunction("crow3_tree", "feathers", ::play_feather_fx, "outtro");
  level thread addNotetrack_customFunction("crow4_tree", "feathers", ::play_feather_fx, "outtro");
  level thread addNotetrack_customFunction("ftn_walker_cross", "fire", ::send_fire_notify, "walk");
  level thread addNotetrack_customFunction("hero", "gun_pickup", ::take_fake_ppsh, "resnov_jump");
  level thread addNotetrack_customFunction("hero", "gun_drop", ::place_rifle, "resnov_gun");
  level thread addNotetrack_customFunction("hero", "mannequin_push", ::move_mannequin, "mannequin_push");
  level thread addNotetrack_customFunction("hero", "bullet", ::mannequin_fall, "mannequin_push");
  level thread addNotetrack_customFunction("hero", "attach_bar_door", ::bardoor_open, "bar_lift");
  level thread addNotetrack_customFunction("hero", "detach_bar_door", ::bardoor_stop, "bar_lift");
  level thread addNotetrack_customFunction("hero", "attach_bar_door", ::bardoor_open, "bar_lift_only");
  level thread addNotetrack_customFunction("hero", "detach_bar_door", ::bardoor_stop, "bar_lift_only");
  level thread addNotetrack_customFunction("horchguy2", "attach", ::chair_delete, "intro");
  level thread addNotetrack_customFunction("horchguy2", "detach", ::chair_replace, "intro");
  level thread addNotetrack_customFunction("sniperL_shoot", "sniper_fire", ::play_glint_fx, "shoot_left_hi");
  level thread addNotetrack_customFunction("sniperL_shoot", "sniper_fire", ::play_glint_fx, "shoot_left_low");
  level thread addNotetrack_customFunction("sniperL_shoot", "sniper_fire", ::play_glint_fx, "shoot_pass");
  level thread addNotetrack_customFunction("sniperR_shoot", "sniper_fire", ::play_glint_fx, "shoot_right_hi");
  level thread addNotetrack_customFunction("sniperR_shoot", "sniper_fire", ::play_glint_fx, "shoot_right_low");
  level thread addNotetrack_customFunction("sniperR_shoot", "sniper_fire", ::play_glint_fx, "shoot_pass");
  level thread addNotetrack_customFunction("hero", "dialog", ::test_time, "resnov_jump");
  level thread addNotetrack_customFunction("hero", "beam", ::beam_lift, "resnov_beam_up");
  level thread addNotetrack_customFunction("beams", "beam", ::player_beam_anims, "fall");
  level thread addNotetrack_customFunction("player_hands", "smack", ::shake_player_effect, "fall");
  level thread addNotetrack_customFunction("player_hands", "resnov", ::call_resnov, "move");
  level thread addNotetrack_customFunction("chandelier", "start_collapse", ::chandolier_fall_notify, "loop");
  level thread addNotetrack_customFunction("hero", "door_open", ::open_slow_door, "building_spin_door");
  level thread addNotetrack_customFunction("bookshelf", "bookshelf_hits", ::bookcase_fx, "fall");
  level thread addNotetrack_customFunction("burner", "fire", ::end_burst, "g_ally_vig");
  level thread addNotetrack_customFunction("burner", "flame", ::alley_flamer_fire_control, "g_ally_vig");
  level thread addNotetrack_customFunction("kicker", "leader", ::spawn_alley_leader, "g_ally_vig");
  level thread addNotetrack_customFunction("kicker", "flamer", ::spawn_alley_flamer, "g_ally_vig");
  level thread addNotetrack_customFunction("kicker", "shot", ::killme, "g_ally_vig");
  level thread addNotetrack_customFunction("kickers_friend", "shot", ::killme, "g_ally_vig");
  level thread addNotetrack_customFunction("burner", "shot", ::killme, "g_ally_vig");
  level thread addNotetrack_customFunction("hero", "detach", ::switch_weapon_out, "kicked_vignette");
  level thread addNotetrack_customFunction("redshirt", "attach", ::redshirt_pickup_gun, "postbb_redshirt2");
  level thread addNotetrack_customFunction("redshirt", "detach", ::redshirt_putdownup_gun, "postbb_redshirt2");
  level thread addNotetrack_customFunction("hero", "attach", ::switch_weapon_in, "postbb_hero");
  level thread addNotetrack_customFunction("hero", "Sni1_IGD_000A_REZN", ::shoo_crow, "resnov_crawl");
  level thread addNotetrack_customFunction("hero", "dialog", ::horchhide_cutoff, "e1_street_horchhide");
  level thread addNotetrack_customFunction("hero", "dialog", ::mark_my_words, "bar_lift_only");
  level thread addNotetrack_customFunction("fountain_woundedguy1", "tick", ::wounded_counter, "wounded");
  level thread addNotetrack_attach("horchguy2", "attach", "anim_berlin_wood_chair_2", "tag_weapon_left", "intro");
  level thread addNotetrack_detach("horchguy2", "detach", "anim_berlin_wood_chair_2", "tag_weapon_left", "intro");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_000A_REZN", "resnov_crawl", "Sni1_IGD_000A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_001A_REZN", "resnov_crawl", "Sni1_IGD_001A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_100A_REZN", "resnov_crawl", "Sni1_IGD_100A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_101A_REZN", "resnov_crawl", "Sni1_IGD_101A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "bar_lift_a", "Sni1_IGD_035A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "bar_lift_a", "Sni1_IGD_037A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "bar_lift_a", "Sni1_IGD_038A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "bar_lift_c", "Sni1_IGD_040A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "bar_lift_c", "Sni1_IGD_041A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "bar_wave", "Sni1_IGD_042A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "building_spin", "Sni1_IGD_043A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "building_spin_door", "Sni1_IGD_044A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "e1_street_horchhide", "Sni1_IGD_031A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "e1_street_horchhide", "Sni1_IGD_032A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "e1_street_horchhide", "Sni1_IGD_002A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "e1_street_horchhide", "Sni1_IGD_033A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "resnov_jump", "Sni1_IGD_030A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "resnov_jump", "Sni1_IGD_042A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_045A_REZN", "pacing_car_truck", "Sni1_IGD_045A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_046A_REZN", "pacing_truck_window", "Sni1_IGD_046A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_049A_REZN", "stair_wait", "Sni1_IGD_049A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_050A_REZN_A", "stair_out", "Sni1_IGD_050A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_047A_REZN", "pacing_window_roll", "Sni1_IGD_047A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_048A_REZN", "pacing_window_roll", "Sni1_IGD_048A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_051A_REZN_A", "mannequin_entrance", "Sni1_IGD_051A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_700A_REZN", "mannequin_entrance", "Sni1_IGD_700A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_052A_REZN_B", "mannequin_entrance", "Sni1_IGD_052A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_053A_REZN_B", "mannequin_entrance_dialog", "Sni1_IGD_053A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_054A_REZN_A", "mannequin_in", "Sni1_IGD_054A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_055A_REZN_A", "mannequin_in", "Sni1_IGD_055A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_056A_REZN_A", "mannequin_loop1_dialog2", "Sni1_IGD_056A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_057A_REZN_A", "mannequin_loop1_dialog1", "Sni1_IGD_057A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_058A_REZN", "mannequin_loop1_dialog3", "Sni1_IGD_058A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_059A_REZN", "mannequin_loop1_dialog4", "Sni1_IGD_059A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_060A_REZN", "mannequin_push", "Sni1_IGD_060A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_061A_REZN", "mannequin_back", "Sni1_IGD_061A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_058A_REZN", "mannequin_loop1_dialog3", "Sni1_IGD_058A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_059A_REZN", "mannequin_loop1_dialog4", "Sni1_IGD_059A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_062A_REZN_A", "mannequin_loop3_dialog1", "Sni1_IGD_062A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_063A_REZN_B", "mannequin_loop3_dialog1", "Sni1_IGD_063A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_064A_REZN_A", "mannequin_loop3_dialog1", "Sni1_IGD_064A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_065A_REZN_A", "mannequin_loop3_dialog1", "Sni1_IGD_065A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_003B_REZN", "resnov_gun", "Sni1_IGD_003B_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_004A_REZN", "resnov_info2", "Sni1_IGD_004A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_005A_REZN", "resnov_info2", "Sni1_IGD_005A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_006A_REZN", "resnov_info2", "Sni1_IGD_006A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_008A_REZN", "resnov_talk", "Sni1_IGD_008A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_009A_REZN", "resnov_talk", "Sni1_IGD_009A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_010A_REZN", "resnov_talk", "Sni1_IGD_010A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_011A_REZN", "resnov_talk", "Sni1_IGD_011A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_012A_REZN", "resnov_talk", "Sni1_IGD_012A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_013A_REZN", "resnov_talk", "Sni1_IGD_013A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_102A_REZN", "resnov_talk", "Sni1_IGD_102A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_054A_REZN", "ftn_ready", "Sni1_IGD_054A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_015A_REZN", "ftn_shootnow", "Sni1_IGD_015A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_016A_REZN", "ftn_again", "Sni1_IGD_016A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_020A_REZN", "ftn_aimright", "Sni1_IGD_020A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_024A_REZN", "ftn_ha", "Sni1_IGD_024A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_023A_REZN", "ftn_hurry", "Sni1_IGD_023A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_018A_REZN", "ftn_moreleft", "Sni1_IGD_018A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_017A_REZN", "ftn_moreright", "Sni1_IGD_017A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_021A_REZN", "ftn_straight", "Sni1_IGD_021A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_026A_REZN", "ftn_dog", "Sni1_IGD_026A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_029A_REZN", "ftn_excellent_aim", "Sni1_IGD_029A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_028A_REZN", "ftn_aim_good", "Sni1_IGD_028A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_027A_REZN", "ftn_could_b_quicker", "Sni1_IGD_027A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_200A_REZN", "ftn_burning_car", "Sni1_IGD_200A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_201A_REZN", "ftn_bystairs", "Sni1_IGD_201A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_215A_REZN", "resnov_beam_up", "Sni1_IGD_215A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_216A_REZN", "resnov_beam_up", "Sni1_IGD_216A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_074A_REZN", "bb_intro_dive", "Sni1_IGD_074A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_075A_REZN", "bb_intro_dive", "Sni1_IGD_075A_REZN");
  level thread addnotetrack_dialogue("hero", "Sni1_IGD_076A_REZN", "bb_intro_dive", "Sni1_IGD_076A_REZN");
  level thread addnotetrack_dialogue("redshirt", "dialog", "postbb_redshirt1", "Sni1_IGD_300A_DALE");
  level thread addnotetrack_dialogue("redshirt", "dialog", "postbb_redshirt1", "Sni1_IGD_301A_DALE");
  level thread addnotetrack_dialogue("hero", "dialog", "postbb_hero", "Sni1_IGD_302A_REZN");
  level thread addnotetrack_dialogue("redshirt", "dialog", "postbb_redshirt1", "Sni1_IGD_303A_DALE");
  level thread addnotetrack_dialogue("hero", "dialog", "postbb_hero", "Sni1_IGD_304A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "postbb_hero", "Sni1_IGD_305A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "postbb_hero", "Sni1_IGD_306A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "resnov_splain", "Sni1_IGD_307A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "resnov_splain", "Sni1_IGD_308A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "resnov_splain", "Sni1_IGD_309A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "reznov_cheer", "Sni1_IGD_315A_REZN");
  level thread addnotetrack_dialogue("hero", "dialog", "reznov_cheer", "Sni1_IGD_400A_REZN");
  level thread addnotetrack_dialogue("kickers_friend", "dialog", "g_ally_vig", "Sni1_IGD_701A_GER1");
  level thread addnotetrack_dialogue("kickers_friend", "dialog", "g_ally_vig", "Sni1_IGD_702A_GER1");
  addnotetrack_fxontag("streetdude1", "idle", "cig_light", "cigarette_glow_puff", "tag_fx");
  addnotetrack_fxontag("streetdude1", "idle", "cig_puff", "cigarette_exhale", "TAG_EYE");
  level.scr_anim["generic"]["patrol_walk"] = % patrol_bored_patrolwalk;
  level.scr_anim["generic"]["patrol_walk_twitch"] = % patrol_bored_patrolwalk_twitch;
  level.scr_anim["generic"]["patrol_stop"] = % patrol_bored_walk_2_bored;
  level.scr_anim["generic"]["patrol_start"] = % patrol_bored_2_walk;
  level.scr_anim["generic"]["patrol_turn180"] = % patrol_bored_2_walk_180turn;
  level.scr_anim["generic"]["patrol_idle_1"] = % patrol_bored_idle;
  level.scr_anim["generic"]["patrol_idle_2"] = % patrol_bored_idle;
  level.scr_anim["generic"]["patrol_idle_3"] = % patrol_bored_idle;
  level.scr_anim["generic"]["patrol_idle_4"] = % patrol_bored_twitch_bug;
  level.scr_anim["generic"]["patrol_idle_5"] = % patrol_bored_twitch_bug;
  level.scr_anim["generic"]["patrol_idle_6"] = % patrol_bored_twitch_stretch;
  level.scr_anim["generic"]["patrol_idle_smoke"] = % patrol_bored_idle;
  level.scr_anim["generic"]["patrol_idle_checkphone"] = % patrol_bored_twitch_bug;
  level.scr_anim["generic"]["patrol_idle_stretch"] = % patrol_bored_twitch_stretch;
  level.scr_anim["generic"]["patrol_idle_phone"] = % patrol_bored_idle;
  level.scr_anim["generic"]["patrol_idle_1_loop"][0] = % patrol_bored_idle;
  level.scr_anim["generic"]["patrol_turn180"] = % patrol_bored_2_walk_180turn;
  level.scr_anim["generic"]["_stealth_patrol_jog"] = % combat_jog;
  level.scr_anim["generic"]["_stealth_patrol_walk"] = % patrol_bored_patrolwalk;
  level.scr_anim["generic"]["_stealth_combat_jog"] = % combat_jog;
  level.scr_anim["generic"]["_stealth_patrol_search_a"] = % patrol_boredwalk_lookcycle_A;
  level.scr_anim["generic"]["_stealth_patrol_search_b"] = % patrol_boredwalk_lookcycle_B;
  level.scr_anim["generic"]["_stealth_behavior_whizby_3"] = % exposed_idle_twitch_v4;
  level.scr_anim["generic"]["_stealth_behavior_whizby_4"] = % run_pain_stumble;
  level.scr_anim["generic"]["_stealth_behavior_spotted_short"] = % exposed_idle_twitch_v4;
  level.scr_anim["generic"]["_stealth_behavior_spotted_long"] = % patrol_bored_react_walkstop_short;
  level.scr_anim["generic"]["_stealth_look_around1"] = % patrol_bored_react_look_v1;
  level.scr_anim["generic"]["_stealth_look_around2"] = % patrol_bored_react_look_v2;
  level.scr_anim["generic"]["_stealth_behavior_saw_corpse"] = % exposed_idle_twitch_v4;
  level.scr_anim["generic"]["_stealth_behavior_generic1"] = % patrol_bored_react_look_advance;
  level.scr_anim["generic"]["_stealth_behavior_generic2"] = % patrol_bored_react_look_retreat;
  level.scr_anim["generic"]["_stealth_behavior_generic3"] = % patrol_bored_react_walkstop;
  level.scr_anim["generic"]["_stealth_behavior_generic4"] = % patrol_bored_react_walkstop_short;
  level.scr_anim["generic"]["_stealth_find_jog"] = % patrol_boredjog_find;
  level.scr_anim["generic"]["lookaround1"] = % patrol_bored_react_look_v1;
  level.scr_anim["generic"]["lookaround2"] = % patrol_bored_react_look_v2;
  level.scr_anim["generic"]["lookaround1_loop"][0] = % patrol_bored_react_look_v1;
  level.scr_anim["generic"]["lookaround2_loop"][0] = % patrol_bored_react_look_v2;
  level.scr_anim["generic"]["street_patrol1"] = % patrol_bored_patrolwalk;
  level.scr_anim["generic"]["street_patrol2"] = % patrol_bored_patrolwalk;
  level.scr_anim["generic"]["street_patrol3"] = % patrol_bored_patrolwalk;
  level.scr_anim["fountain_woundedguy1"]["wounded"] = % ch_sniper_fountain_rus1;
  level.scr_anim["fountain_woundedguy1"]["wounded_loop"] = % ch_sniper_fountain_rus1_loop;
  level.scr_anim["fountain_woundedguy1"]["wounded_loop_timed"] = % ch_sniper_fountain_rus1_loop;
  level.scr_anim["fountain_woundedguy1"]["dead_loop"][0] = % ch_sniper_fountain_rus1_dead;
  level.scr_anim["fountain_woundedguy1"]["stay_dead"] = % ch_sniper_fountain_rus1_dead;
  level.scr_anim["fountain_woundedguy2"]["wounded"] = % ch_sniper_fountain_rus2;
  level.scr_anim["fountain_woundedguy2"]["wounded_loop"][0] = % ch_sniper_fountain_rus2_loop;
  level.scr_anim["fountain_woundedguy2"]["dead_loop"][0] = % ch_sniper_fountain_rus2_dead;
  level.scr_anim["fountain_woundedguy2"]["stay_dead"] = % ch_sniper_fountain_rus2_dead;
  level.scr_anim["fountain_woundedguy3"]["wounded"] = % ch_sniper_fountain_rus3;
  level.scr_anim["fountain_woundedguy3"]["dead_loop"][0] = % ch_sniper_fountain_rus3_dead;
  level.scr_anim["fountain_woundedguy3"]["stay_dead"] = % ch_sniper_fountain_rus3_dead;
  level.scr_anim["gunner"]["gun_dudes"] = % ch_sniper_fountain_german;
  level.scr_anim["tankriders"]["rider1"][0] = % ch_sniper_panzer4_passenger10_idle;
  level.scr_anim["tankriders"]["rider2"][0] = % ch_sniper_panzer4_passenger8_idle;
  level.scr_anim["tankriders"]["rider3"][0] = % ch_sniper_panzer4_passenger4_idle;
  level.scr_anim["tankriders"]["lookaround1"] = % ch_sniper_panzer4_passenger10_lookaround;
  level.scr_anim["tankriders"]["lookaround2"] = % ch_sniper_panzer4_passenger8_lookaround;
  level.scr_anim["tankriders"]["lookaround3"] = % ch_sniper_panzer4_passenger4_lookaround;
  level.scr_anim["ftn_walker_cross"]["walk"] = % ch_sniper_poking_dead_guy1;
  level.scr_anim["ftn_walker_side"]["walk"] = % ch_sniper_poking_dead_guy2;
  level.scr_anim["ftn_walker_last"]["walk"] = % ch_sniper_poking_dead_guy3;
  level.scr_anim["ftn_walker_last"]["patrolwalk"] = % patrol_bored_patrolwalk;
  level.scr_anim["ftn_walker"]["dude4"] = % ch_sniper_poking_dead_guy4;
  level.scr_anim["ftn_walker"]["patrolwalk"] = % patrol_bored_patrolwalk;
  level.scr_anim["officer"]["officer_ride"] = % ch_sniper_intro_passenger;
  level.scr_anim["assistant"]["assistant_ride"] = % ch_sniper_intro_driver;
  level.scr_anim["streetdude1"]["idle"][0] = % ch_sniper_ambient2_guy1_idle;
  level.scr_anim["streetdude1"]["intro"] = % ch_sniper_ambient2_guy1_intro;
  level.scr_anim["streetdude1"]["loop"][0] = % ch_sniper_ambient2_guy1_loop;
  level.scr_anim["streetdude1"]["react"] = % ch_sniper_ambient2_guy1_react;
  level.scr_anim["streetdude1"]["shot"] = % ch_sniper_ambient2_guy1_shot;
  level.scr_anim["streetdude2"]["intro"] = % ch_sniper_ambient2_guy2_intro;
  level.scr_anim["streetdude2"]["loop"][0] = % ch_sniper_ambient2_guy2_loop;
  level.scr_anim["streetdude2"]["react"] = % ch_sniper_ambient2_guy2_react;
  level.scr_anim["streetdude2"]["shot"] = % ch_sniper_ambient2_guy2_shot;
  level.scr_anim["streetdude3"]["intro"] = % ch_sniper_ambient1_guy1_intro;
  level.scr_anim["streetdude3"]["loop"][0] = % ch_sniper_ambient1_guy1_loop;
  level.scr_anim["streetdude3"]["react"] = % ch_sniper_ambient1_guy1_react;
  level.scr_anim["streetdude3"]["shot"] = % ch_sniper_ambient1_guy1_shot;
  level.scr_anim["streetdude4"]["intro"] = % ch_sniper_ambient1_guy2_intro;
  level.scr_anim["streetdude4"]["loop"][0] = % ch_sniper_ambient1_guy2_loop;
  level.scr_anim["streetdude4"]["react"] = % ch_sniper_ambient1_guy2_react;
  level.scr_anim["streetdude4"]["shot"] = % ch_sniper_ambient1_guy2_shot;
  level.scr_anim["dog_handler"]["find_body"] = % ch_sniper_street_react;
  level.scr_anim["horchguy1"]["intro"] = % ch_sniper_horch_guy1_intro;
  level.scr_anim["horchguy1"]["loop"][0] = % ch_sniper_horch_guy1_loop;
  level.scr_anim["horchguy1"]["react"] = % ch_sniper_horch_guy1_react;
  level.scr_anim["horchguy1"]["shot"] = % ch_sniper_horch_guy1_shot;
  level.scr_anim["horchguy1"]["dead"][0] = % ch_sniper_horch_guy1_dead;
  level.scr_anim["horchguy2"]["intro"] = % ch_sniper_horch_guy2_intro;
  level.scr_anim["horchguy2"]["loop"][0] = % ch_sniper_horch_guy2_loop;
  level.scr_anim["horchguy2"]["react"] = % ch_sniper_horch_guy2_react;
  level.scr_anim["horchguy2"]["shot"] = % ch_sniper_horch_guy2_shot;
  level.scr_anim["hunters"]["door_kick"] = % door_bash_and_block;
  level.scr_anim["sniperL"]["idle_L"][0] = % ch_sniper_window_idle_L;
  level.scr_anim["sniperR"]["idle_R"][0] = % ch_sniper_window_idle_R;
  level.scr_anim["sniperL_shoot"]["shoot_left_hi"] = % ch_sniper_shootL_hi;
  level.scr_anim["sniperL_shoot"]["shoot_left_low"] = % ch_sniper_shootL_lo;
  level.scr_anim["sniperR_shoot"]["shoot_right_low"] = % ch_sniper_shootR_lo;
  level.scr_anim["sniperR_shoot"]["shoot_right_hi"] = % ch_sniper_shootR_hi;
  level.scr_anim["sniperL_shoot"]["shoot_pass"] = % ch_sniper_window_pass2_L;
  level.scr_anim["sniperR_shoot"]["shoot_pass"] = % ch_sniper_window_pass2_R;
  level.scr_anim["sniperL_pass"]["pass1L"] = % ch_sniper_window_pass1_L;
  level.scr_anim["sniperR_pass"]["pass1R"] = % ch_sniper_window_pass1_R;
  level.scr_anim["sniperL_pass"]["pass2L"] = % ch_sniper_window_pass3_L;
  level.scr_anim["sniperR_pass"]["pass2R"] = % ch_sniper_window_pass3_R;
  level.scr_anim["sniperL_scan"]["scanL_hi"] = % ch_sniper_scanL_hi;
  level.scr_anim["sniperL_scan"]["scanL_lo"] = % ch_sniper_scanL_lo;
  level.scr_anim["sniperR_scan"]["scanR_hi"] = % ch_sniper_scanR_hi;
  level.scr_anim["sniperR_scan"]["scanR_lo"] = % ch_sniper_scanR_lo;
  level.scr_anim["sniper1"]["sneaky_walk1"] = % ai_sneaking_a_walk;
  level.scr_anim["sniper1"]["sniper_death"] = % corner_standR_deathA;
  level.scr_anim["street_runners"]["_stealth_combat_jog"] = % combat_jog;
  level.scr_anim["street_runners"]["run1"] = % ch_sniper_german_motioning1;
  level.scr_anim["street_runners"]["run2"] = % ch_sniper_german_motioning2;
  level.scr_anim["street_runners"]["run3"] = % ch_sniper_german_motioning3;
  level.scr_anim["dog_handler2"]["walk_withdog"] = % ch_sniper_dog_handler;
  level.scr_anim["dog_handler2"]["walk_tospot"] = % patrol_bored_patrolwalk;
  level.scr_anim["e2_flamer"]["stand_aim_reach"] = % ai_flamethrower_aim_5;
  level.scr_anim["e2_flamer"]["stand_aim"][0] = % ai_flamethrower_aim_5;
  level.scr_anim["kicker"]["g_ally_vig"] = % ch_sniper_Resnov_kicked_kicker;
  level.scr_anim["kickers_friend"]["g_ally_vig"] = % ch_sniper_Resnov_kicked_leader;
  level.scr_anim["burner"]["g_ally_vig"] = % ch_sniper_Resnov_kicked_flamer;
  level.scr_anim["officer_guard1"]["talking_loop"][0] = % ch_makinraid_e2_arguing1_loop;
  level.scr_anim["officer_guard2"]["talking_loop"][0] = % ch_makinraid_e2_arguing2_loop;
  level.scr_anim["allies"]["molotov_toss"] = % coverstand_grenadeA;
  level.scr_anim["flamer"]["idle"][0] = % patrol_bored_idle;
  level.scr_anim["e3_smoker1"]["smoke_it"][0] = % ch_holland2_smoking_guy1;
  level.scr_anim["e3_smoker2"]["smoke_it"][0] = % ch_holland2_smoking_guy2;
  level.scr_anim["driver"]["driver_under_fire"][0] = % crew_jeep1_driver_drive_under_fire;
  level.scr_anim["driver"]["driver_death"] = % crew_jeep1_driver_death_shot;
  level.scr_anim["driver"]["driver_death_loop"][0] = % crew_jeep1_driver_death_shot_loop;
  level.scr_anim["officer"]["oficer_ride_back"][0] = % ch_sniper_amsel_horch_loop;
  level.scr_anim["officer"]["low_walk"] = % ai_sneaking_a_walk;
  level.scr_anim["officer"]["crouchhide"][0] = % ch_sniper_amsel_cover_idle;
  level.scr_anim["officer"]["cover_run"] = % ch_sniper_amsel_cover_run;
  level.scr_anim["officer"]["run_cover"] = % ch_sniper_amsel_run_cover;
  level.scr_anim["officer"]["amsel_shot"] = % ch_sniper_amsel_death;
  level.scr_anim["officer"]["run_cautious"] = % ch_sniper_amsel_run_cautious;
  level.scr_anim["officer"]["last_run"] = % ch_sniper_amsel_run_hurry;
  level.scr_anim["officer"]["run_away"] = % ch_sniper_amsel_run_away;
  level.scr_anim["officer"]["run_quickly"] = % ch_sniper_amsel_run_quickly;
  level.scr_anim["officer"]["bodyguard_exit"] = % ch_sniper_amsel_exit;
  level.scr_anim["officers_sniper"]["bodyguard_exit"] = % ch_sniper_bodyguard_exit;
  level.scr_anim["officers_sniper"]["loop_l"][0] = % ch_sniper_crouch_loop_l;
  level.scr_anim["officers_sniper"]["loop_r"][0] = % ch_sniper_crouch_loop_r;
  level.scr_anim["officers_sniper"]["shoot_l"] = % ch_sniper_crouch_shoot_l;
  level.scr_anim["officers_sniper"]["shoot_r"] = % ch_sniper_crouch_shoot_r;
  level.scr_anim["generic"]["motioning"][0] = % ch_sniper_entourage_motioning;
  level.scr_anim["generic"]["motioning_reach"] = % ch_sniper_entourage_motioning;
  level.scr_anim["generic"]["point"] = % ch_sniper_entourage_point;
  level.scr_anim["generic"]["scan"] = % ch_sniper_entourage_scan;
  level.scr_anim["generic"]["wave_ansel"] = % ch_sniper_entourage_waving;
  level.scr_anim["officer"]["horch_getin"] = % ch_sniper_amsel_getin;
  level.scr_anim["officer"]["horch_getout"] = % ch_sniper_amsel_getout;
  level.scr_anim["driver"]["horch_getin"] = % ch_sniper_amsel_getin_driver;
  level.scr_anim["officer"]["horch_death"] = % ch_sniper_amsel_horch_die;
  level.scr_anim["officer"]["horch_deathloop"] = % ch_sniper_amsel_horch_die_loop;
  level.scr_anim["officer"]["horch_lookback"] = % ch_sniper_amsel_horch_lookback;
  level.scr_anim["officer"]["horch_wave1"] = % ch_sniper_amsel_horch_wave1;
  level.scr_anim["officer"]["horch_wave2"] = % ch_sniper_amsel_horch_wave2;
  level.scr_anim["hero"]["resnov_gun"] = % ch_sniper_fountain_resnov_gun;
  level.scr_anim["hero"]["resnov_crawl"] = % ch_sniper_fountain_resnov_crawl;
  level.scr_anim["hero"]["resnov_info"] = % ch_sniper_fountain_resnov_info;
  level.scr_anim["hero"]["resnov_talk"] = % ch_sniper_Resnov_fountain_talk;
  level.scr_anim["hero"]["resnov_info2"] = % ch_sniper_fountain_resnov_info2;
  level.scr_anim["hero"]["resnov_intro_loop"][0] = % ch_sniper_fountain_resnov_intro_loop;
  level.scr_anim["hero"]["resnov_jump"] = % ch_sniper_fountain_resnov_jump;
  level.scr_anim["hero"]["resnov_wait_loop"][0] = % ch_sniper_fountain_resnov_wait_loop;
  level.scr_anim["hero"]["resnov_gun_loop"][0] = % ch_sniper_fountain_resnov_gun_loop;
  level.scr_anim["hero"]["ftn_ready"] = % ch_sniper_Resnov_fountain_ready;
  level.scr_anim["hero"]["ftn_shootnow"] = % ch_sniper_Resnov_fountain_shootnow;
  level.scr_anim["hero"]["ftn_again"] = % ch_sniper_Resnov_fountain_again;
  level.scr_anim["hero"]["ftn_again_loop"][0] = % ch_sniper_Resnov_fountain_peekloop;
  level.scr_anim["hero"]["ftn_aimright"] = % ch_sniper_Resnov_fountain_aimright;
  level.scr_anim["hero"]["ftn_ha"] = % ch_sniper_Resnov_fountain_ha;
  level.scr_anim["hero"]["ftn_hurry"] = % ch_sniper_Resnov_fountain_hurry;
  level.scr_anim["hero"]["ftn_moreleft"] = % ch_sniper_Resnov_fountain_moreleft;
  level.scr_anim["hero"]["ftn_moreright"] = % ch_sniper_Resnov_fountain_moreright;
  level.scr_anim["hero"]["ftn_straight"] = % ch_sniper_Resnov_fountain_straightahead;
  level.scr_anim["hero"]["ftn_dog"] = % ch_sniper_Resnov_fountain_dog;
  level.scr_anim["hero"]["ftn_excellent_aim"] = % ch_sniper_Resnov_fountain_aimexcellent;
  level.scr_anim["hero"]["ftn_aim_good"] = % ch_sniper_Resnov_fountain_aimgood;
  level.scr_anim["hero"]["ftn_could_b_quicker"] = % ch_sniper_Resnov_fountain_aimpoor;
  level.scr_anim["hero"]["ftn_burning_car"] = % ch_sniper_Resnov_fountain_byburningcar;
  level.scr_anim["hero"]["ftn_bystairs"] = % ch_sniper_Resnov_fountain_bystairs;
  level.scr_anim["hero"]["e1_street_horchhide"] = % ch_sniper_Resnov_horch_hide;
  level.scr_anim["hero"]["e1_street_run"] = % ch_reznov_run_d;
  level.scr_anim["hero"]["e1_street_followme"] = % ch_sniper_Resnov_followme;
  level.scr_anim["hero"]["e1_street_windowhop"] = % ch_sniper_Resnov_window;
  level.scr_anim["hero"]["sneaky_walk1"] = % ai_sneaking_a_walk;
  level.scr_anim["hero"]["building_spin"] = % ch_sniper_Resnov_clearing;
  level.scr_anim["hero"]["building_spin_door"] = % ch_sniper_Resnov_clearing_door;
  level.scr_anim["hero"]["bar_lift_only"] = % ch_sniper_Resnov_bar_b;
  level.scr_anim["hero"]["bar_lift_a"] = % ch_sniper_Resnov_bar_a;
  level.scr_anim["hero"]["bar_lift_c"] = % ch_sniper_Resnov_bar_c;
  level.scr_anim["hero"]["bar_wait"][0] = % ch_sniper_Resnov_bar_wait;
  level.scr_anim["hero"]["bar_wave"] = % ch_sniper_Resnov_bar_wave;
  level.scr_anim["hero"]["door_wait"][0] = % ch_sniper_Resnov_door_wait;
  level.scr_anim["hero"]["pacing_car_in"] = % ch_sniper_Resnov_car_in;
  level.scr_anim["hero"]["pacing_car_idle1"][0] = % ch_sniper_Resnov_car_idle1;
  level.scr_anim["hero"]["pacing_car_idle1_reach"] = % ch_sniper_Resnov_car_idle1;
  level.scr_anim["hero"]["pacing_car_truck"] = % ch_sniper_Resnov_car_truck;
  level.scr_anim["hero"]["pacing_truck_idle"][0] = % ch_sniper_Resnov_truck_idle;
  level.scr_anim["hero"]["pacing_truck_idle_reach"] = % ch_sniper_Resnov_truck_idle;
  level.scr_anim["hero"]["pacing_truck_window"] = % ch_sniper_Resnov_truck_window;
  level.scr_anim["hero"]["pacing_window_loop"][0] = % ch_sniper_Resnov_window_loop;
  level.scr_anim["hero"]["pacing_window_loop_reach"] = % ch_sniper_Resnov_window_loop;
  level.scr_anim["hero"]["pacing_window_roll"] = % ch_sniper_Resnov_window_roll;
  level.scr_anim["hero"]["pacing_window_roll_stand"] = % prone_2_stand;
  level.scr_anim["hero"]["stair_run"] = % ai_staircase_run_up_v1;
  level.scr_anim["hero"]["stairs_down"] = % ai_staircase_run_down_v1;
  level.scr_anim["hero"]["stair_wait_loop"][0] = % ch_sniper_store_stair_wait_loop;
  level.scr_anim["hero"]["stair_wait"] = % ch_sniper_store_stair_wait;
  level.scr_anim["hero"]["stair_in"] = % ch_sniper_store_stair_in;
  level.scr_anim["hero"]["stair_out"] = % ch_sniper_store_stair_out;
  level.scr_anim["hero"]["mannequin_entrance"] = % ch_sniper_mannequin_entrance;
  level.scr_anim["hero"]["mannequin_entrance_dialog"] = % ch_sniper_mannequin_entrance_dialog;
  level.scr_anim["hero"]["mannequin_wait"][0] = % ch_sniper_mannequin_wait;
  level.scr_anim["hero"]["mannequin_in"] = % ch_sniper_mannequin_in;
  level.scr_anim["hero"]["mannequin_out"] = % ch_sniper_mannequin_out;
  level.scr_anim["hero"]["mannequin_slide_in"] = % ch_sniper_resnov_mannequin_in;
  level.scr_anim["hero"]["mannequin_loop1"][0] = % ch_sniper_Resnov_mannequin_loop1;
  level.scr_anim["hero"]["mannequin_loop1_reach"] = % ch_sniper_Resnov_mannequin_loop1;
  level.scr_anim["hero"]["mannequin_loop1_dialog1"] = % ch_sniper_Resnov_mannequin_loop1_dialog1;
  level.scr_anim["hero"]["mannequin_loop1_dialog2"] = % ch_sniper_Resnov_mannequin_loop1_dialog2;
  level.scr_anim["hero"]["mannequin_loop1_dialog3"] = % ch_sniper_Resnov_mannequin_loop1_dialog3;
  level.scr_anim["hero"]["mannequin_loop1_dialog4"] = % ch_sniper_Resnov_mannequin_loop1_dialog4;
  level.scr_anim["hero"]["mannequin_loop3_dialog1"] = % ch_sniper_Resnov_mannequin_loop3_dialog1;
  level.scr_anim["hero"]["mannequin_loop3_dialog2"] = % ch_sniper_Resnov_mannequin_loop3_dialog2;
  level.scr_anim["hero"]["mannequin_loop3_dialog3"] = % ch_sniper_Resnov_mannequin_loop3_dialog3;
  level.scr_anim["hero"]["mannequin_loop3"][0] = % ch_sniper_Resnov_mannequin_loop3;
  level.scr_anim["hero"]["mannequin_push"] = % ch_sniper_Resnov_mannequin_push;
  level.scr_anim["hero"]["mannequin_endpush_loop"][0] = % ch_sniper_Resnov_mannequin_wait;
  level.scr_anim["hero"]["mannequin_back"] = % ch_sniper_Resnov_mannequin_back;
  level.scr_anim["hero"]["bb_intro_dive"] = % ch_sniper_Resnov_clock_dive;
  level.scr_anim["hero"]["bb_intro_staylow"] = % ch_sniper_Resnov_clock_keeplow;
  level.scr_anim["hero"]["bb_intro_loop"][0] = % ch_sniper_Resnov_clock_loop;
  level.scr_anim["hero"]["bb_intro_loop_reach"] = % ch_sniper_Resnov_clock_loop;
  level.scr_anim["hero"]["bb_intro_hop_down"] = % ch_sniper_resnov_hop;
  level.scr_anim["hero"]["bb_intro_hop"] = % ch_sniper_Resnov_table;
  level.scr_anim["hero"]["bb_intro_hop_loop"][0] = % ch_sniper_Resnov_table_loop;
  level.scr_anim["hero"]["bb_crawl_getup"] = % ch_sniper_Resnov_crawl_getup;
  level.scr_anim["hero"]["bb_jumpout"] = % ch_sniper_Resnov_explosion;
  level.scr_anim["hero"]["bb_jumproll"] = % ch_sniper_Resnov_landing;
  level.scr_anim["hero"]["bb_proneloop"][0] = % ch_sniper_Resnov_land_loop;
  level.scr_anim["hero"]["bb_getup"] = % ch_sniper_Resnov_land_getup;
  level.scr_anim["hero"]["bb_stairs_in"] = % ch_sniper_Resnov_stairs_in;
  level.scr_anim["hero"]["bb_stairs_loop"][0] = % ch_sniper_Resnov_stairs_loop;
  level.scr_anim["hero"]["bb_stairs_loop_reach"] = % ch_sniper_Resnov_stairs_loop;
  level.scr_anim["hero"]["bb_stairs_out"] = % ch_sniper_Resnov_stairs_out;
  level.scr_anim["hero"]["runcough1"] = % ch_resnov_runandcough1;
  level.scr_anim["hero"]["bb_stumble4"] = % ch_sniper_resnov_stumble4;
  level.scr_anim["hero"]["bb_stumble3"] = % ch_sniper_resnov_stumble2;
  level.scr_anim["hero"]["bb_stumble1"] = % ch_sniper_resnov_stumble1;
  level.scr_anim["hero"]["resnov_beam_up"] = % ch_sniper_Resnov_beam;
  level.scr_anim["hero"]["resnov_hole_wait"][0] = % ch_sniper_Resnov_wait_loop1;
  level.scr_anim["hero"]["resnov_hole_wait_reach"] = % ch_sniper_Resnov_wait_loop1;
  level.scr_anim["hero"]["resnov_hole_talk"] = % ch_sniper_Resnov_wait;
  level.scr_anim["hero"]["patrol_walk"] = % patrol_bored_patrolwalk;
  level.scr_anim["redshirt"]["postbb_redshirt1"] = % ch_sniper_ladder_redshirt1;
  level.scr_anim["redshirt"]["postbb_redshirt2"] = % ch_sniper_ladder_redshirt2;
  level.scr_anim["redshirt"]["postbb_redshirt3"] = % ch_sniper_ladder_redshirt3;
  level.scr_anim["hero"]["postbb_hero"] = % ch_sniper_ladder_resnov;
  level.scr_anim["hero"]["kicked_vignette"] = % ch_sniper_Resnov_kicked;
  level.scr_anim["hero"]["kicked_loop"][0] = % ch_sniper_Resnov_kicked_loop;
  level.scr_anim["hero"]["resnov_splain"] = % ch_sniper_resnov_explain;
  level.scr_anim["hero"]["resnov_splain_loop"][0] = % ch_sniper_resnov_explain_loop;
  level.scr_anim["hero"]["tankblast_dive"] = % ch_sniper_Resnov_clock_dive;
  level.scr_anim["hero"]["door_open3"] = % ch_holland3_door_bash;
  level.scr_anim["hero"]["swimming"][0] = % ch_pby_float1;
  level.scr_anim["hero"]["reznov_cheer_dive"] = % ch_sniper_resnov_cheer_dive;
  level.scr_anim["hero"]["reznov_cheer"] = % ch_sniper_resnov_cheer;
  level.scr_anim["hero"]["reznov_fall_towater"] = % ch_sniper_resnov_last_fall;
  level.scr_anim["hero"]["reznov_jump_towater"] = % ch_sniper_resnov_last_jump;
  level.scr_anim["hero"]["rambov"] = % ch_sniper_resnov_runandshoot;
  level.scr_anim["hero"]["reznov_jump_towater_loop"][0] = % ch_sniper_resnov_last_jump_loop;
  level.scr_anim["hero"]["reznov_jump_towater_loop_reach"] = % ch_sniper_resnov_last_jump_loop;
  level.scr_sound["hero"]["shh"] = "Sni1_IGD_000A_REZN";
  level.scr_sound["hero"]["need_help"] = "Sni1_IGD_001A_REZN";
  level.scr_sound["hero"]["stay_low"] = "Sni1_IGD_002A_REZN";
  level.scr_sound["hero"]["take_rifle"] = "Sni1_IGD_003B_REZN";
  level.scr_sound["hero"]["mudak"] = "Sni1_IGD_004A_REZN";
  level.scr_sound["hero"]["city_fallen"] = "Sni1_IGD_005A_REZN";
  level.scr_sound["hero"]["hes_lucky"] = "Sni1_IGD_006A_REZN";
  level.scr_sound["hero"]["fingers_torn"] = "Sni1_IGD_007A_REZN";
  level.scr_sound["hero"]["load_rifle"] = "Sni1_IGD_008A_REZN";
  level.scr_sound["hero"]["wait_overhead"] = "Sni1_IGD_009A_REZN";
  level.scr_sound["hero"]["engines_drown"] = "Sni1_IGD_010A_REZN";
  level.scr_sound["hero"]["like_hunting"] = "Sni1_IGD_011A_REZN";
  level.scr_sound["hero"]["wrong_time"] = "Sni1_IGD_012A_REZN";
  level.scr_sound["hero"]["not_time"] = "Sni1_IGD_013A_REZN";
  level.scr_sound["hero"]["not_yet"] = "Sni1_IGD_014A_REZN";
  level.scr_sound["hero"]["shootnow"] = "Sni1_IGD_015A_REZN";
  level.scr_sound["hero"]["again"] = "Sni1_IGD_016A_REZN";
  level.scr_sound["hero"]["moreright"] = "Sni1_IGD_017A_REZN";
  level.scr_sound["hero"]["moreleft"] = "Sni1_IGD_018A_REZN";
  level.scr_sound["hero"]["aimleft"] = "Sni1_IGD_019A_REZN";
  level.scr_sound["hero"]["aimright"] = "Sni1_IGD_020A_REZN";
  level.scr_sound["hero"]["straight"] = "Sni1_IGD_021A_REZN";
  level.scr_sound["hero"]["4stillstand"] = "Sni1_IGD_022A_REZN";
  level.scr_sound["hero"]["hurry"] = "Sni1_IGD_023A_REZN";
  level.scr_sound["hero"]["ha"] = "Sni1_IGD_024A_REZN";
  level.scr_sound["hero"]["3_remain"] = "Sni1_IGD_025A_REZN";
  level.scr_sound["hero"]["dog"] = "Sni1_IGD_026A_REZN";
  level.scr_sound["hero"]["could_b_quicker"] = "Sni1_IGD_027A_REZN";
  level.scr_sound["hero"]["aim_good"] = "Sni1_IGD_028A_REZN";
  level.scr_sound["hero"]["excellent_aim"] = "Sni1_IGD_029A_REZN";
  level.scr_sound["hero"]["close_in"] = "Sni1_IGD_030A_REZN";
  level.scr_sound["hero"]["chyort"] = "Sni1_IGD_031A_REZN";
  level.scr_sound["hero"]["armor_patrol"] = "Sni1_IGD_032A_REZN";
  level.scr_sound["hero"]["b4_discover_dead"] = "Sni1_IGD_033A_REZN";
  level.scr_sound["hero"]["real_hunt_begin"] = "Sni1_IGD_034A_REZN";
  level.scr_sound["hero"]["like_rat"] = "Sni1_IGD_035A_REZN";
  level.scr_sound["hero"]["get_chance"] = "Sni1_IGD_036A_REZN";
  level.scr_sound["hero"]["friends_lovers"] = "Sni1_IGD_037A_REZN";
  level.scr_sound["hero"]["no_longer"] = "Sni1_IGD_038A_REZN";
  level.scr_sound["hero"]["mark_mywords"] = "Sni1_IGD_039A_REZN";
  level.scr_sound["hero"]["things_change"] = "Sni1_IGD_040A_REZN";
  level.scr_sound["hero"]["their_blood"] = "Sni1_IGD_041A_REZN";
  level.scr_sound["hero"]["this_way2"] = "Sni1_IGD_042A_REZN";
  level.scr_sound["hero"]["know_routines"] = "Sni1_IGD_043A_REZN";
  level.scr_sound["hero"]["creature_of_habit"] = "Sni1_IGD_044A_REZN";
  level.scr_sound["hero"]["inspects_each"] = "Sni1_IGD_045A_REZN";
  level.scr_sound["hero"]["use_building"] = "Sni1_IGD_046A_REZN";
  level.scr_sound["hero"]["sniper"] = "Sni1_IGD_047A_REZN";
  level.scr_sound["hero"]["inside"] = "Sni1_IGD_048A_REZN";
  level.scr_sound["hero"]["almost_got"] = "Sni1_IGD_049A_REZN";
  level.scr_sound["hero"]["follow_me"] = "Sni1_IGD_050A_REZN";
  level.scr_sound["hero"]["cross_river"] = "Sni1_IGD_051A_REZN";
  level.scr_sound["hero"]["cat_mouse"] = "Sni1_IGD_052A_REZN";
  level.scr_sound["hero"]["draw_fire"] = "Sni1_IGD_053A_REZN";
  level.scr_sound["hero"]["ready"] = "Sni1_IGD_054A_REZN";
  level.scr_sound["hero"]["now"] = "Sni1_IGD_055A_REZN";
  level.scr_sound["hero"]["4_floor_r"] = "Sni1_IGD_056A_REZN";
  level.scr_sound["hero"]["3_floor_r"] = "Sni1_IGD_057A_REZN";
  level.scr_sound["hero"]["4_floor_l"] = "Sni1_IGD_058A_REZN";
  level.scr_sound["hero"]["3_floor_l"] = "Sni1_IGD_059A_REZN";
  level.scr_sound["hero"]["draw_fire_again"] = "Sni1_IGD_060A_REZN";
  level.scr_sound["hero"]["chyort2"] = "Sni1_IGD_061A_REZN";
  level.scr_sound["hero"]["see_him"] = "Sni1_IGD_062A_REZN";
  level.scr_sound["hero"]["he_knows"] = "Sni1_IGD_063A_REZN";
  level.scr_sound["hero"]["cant_risk_it"] = "Sni1_IGD_064A_REZN";
  level.scr_sound["hero"]["stay_out_light"] = "Sni1_IGD_065A_REZN";
  level.scr_sound["hero"]["get_to_window"] = "Sni1_IGD_066A_REZN";
  level.scr_sound["hero"]["find_cover"] = "Sni1_IGD_067A_REZN";
  level.scr_sound["hero"]["u_pinned"] = "Sni1_IGD_068A_REZN";
  level.scr_sound["hero"]["move"] = "Sni1_IGD_069A_REZN";
  level.scr_sound["hero"]["good_hunting"] = "Sni1_IGD_070A_REZN";
  level.scr_sound["hero"]["patrols_heard"] = "Sni1_IGD_071A_REZN";
  level.scr_sound["hero"]["need_tomove"] = "Sni1_IGD_072A_REZN";
  level.scr_sound["hero"]["shh_patrol"] = "Sni1_IGD_073A_REZN";
  level.scr_sound["hero"]["found_us"] = "Sni1_IGD_074A_REZN";
  level.scr_sound["hero"]["we_need_toleave"] = "Sni1_IGD_075A_REZN";
  level.scr_sound["hero"]["hit_floor"] = "Sni1_IGD_076A_REZN";
  level.scr_sound["hero"]["burn_us_out"] = "Sni1_IGD_077A_REZN";
  level.scr_sound["hero"]["stay_low_dontbreathe"] = "Sni1_IGD_078A_REZN";
  level.scr_sound["hero"]["jump"] = "Sni1_IGD_079A_REZN";
  level.scr_sound["hero"]["do_wut_i_say"] = "Sni1_IGD_100A_REZN";
  level.scr_sound["hero"]["injured_hand"] = "Sni1_IGD_101A_REZN";
  level.scr_sound["hero"]["if_we_reveal"] = "Sni1_IGD_102A_REZN";
  level.scr_sound["hero"]["amsel_is_inside"] = "Sni1_IGD_103A_REZN";
  level.scr_sound["hero"]["u_gave_away"] = "Sni1_IGD_104A_REZN";
  level.scr_sound["hero"]["our_chance_is_lost"] = "Sni1_IGD_105A_REZN";
  level.scr_sound["hero"]["get_over_here"] = "Sni1_IGD_106A_REZN";
  level.scr_sound["hero"]["stay_down"] = "Sni1_IGD_107A_REZN";
  level.scr_sound["hero"]["u_gave_away_ur"] = "Sni1_IGD_108A_REZN";
  level.scr_sound["hero"]["shots_tell_him"] = "Sni1_IGD_109A_REZN";
  level.scr_sound["hero"]["burning_car"] = "Sni1_IGD_200A_REZN";
  level.scr_sound["hero"]["bystairs"] = "Sni1_IGD_201A_REZN";
  level.scr_sound["hero"]["its_too_late"] = "Sni1_IGD_203A_REZN";
  level.scr_sound["hero"]["u_should_take_chance"] = "Sni1_IGD_204A_REZN";
  level.scr_sound["hero"]["u_let_chance_slip"] = "Sni1_IGD_205A_REZN";
  level.scr_sound["hero"]["let_them_pass"] = "Sni1_IGD_207A_REZN";
  level.scr_sound["hero"]["b4_burned_alive"] = "Sni1_IGD_208A_REZN";
  level.scr_sound["hero"]["they_r_surround"] = "Sni1_IGD_209A_REZN";
  level.scr_sound["hero"]["we_must_hurry"] = "Sni1_IGD_212A_REZN";
  level.scr_sound["hero"]["move_upstairs"] = "Sni1_IGD_213A_REZN";
  level.scr_sound["hero"]["need_find_way_out"] = "Sni1_IGD_214A_REZN";
  level.scr_sound["hero"]["take_my_hand"] = "Sni1_IGD_215A_REZN";
  level.scr_sound["hero"]["need_u_alive"] = "Sni1_IGD_216A_REZN";
  level.scr_sound["hero"]["Dimitri"] = "Sni1_IGD_300A_DALE";
  level.scr_sound["hero"]["thought_u_dead"] = "Sni1_IGD_301A_DALE";
  level.scr_sound["hero"]["among_but_not1"] = "Sni1_IGD_302A_REZN";
  level.scr_sound["hero"]["assault_com_post"] = "Sni1_IGD_303A_DALE";
  level.scr_sound["hero"]["prevent_calling"] = "Sni1_IGD_304A_REZN";
  level.scr_sound["hero"]["wait_for_screams"] = "Sni1_IGD_305A_REZN";
  level.scr_sound["hero"]["dimitri_this_way"] = "Sni1_IGD_306A_REZN";
  level.scr_sound["hero"]["do_u_see_flame"] = "Sni1_IGD_307A_REZN";
  level.scr_sound["hero"]["choose_moment"] = "Sni1_IGD_308A_REZN";
  level.scr_sound["hero"]["incinerate_anyone"] = "Sni1_IGD_309A_REZN";
  level.scr_sound["hero"]["no_time_to_waste"] = "Sni1_IGD_310A_REZN";
  level.scr_sound["hero"]["take_the_shot"] = "Sni1_IGD_311A_REZN";
  level.scr_sound["hero"]["shoot_fuel_tank"] = "Sni1_IGD_312A_REZN";
  level.scr_sound["hero"]["belly_laugh1"] = "Sni1_IGD_315A_REZN";
  level.scr_sound["hero"]["another_flamer"] = "Sni1_IGD_316A_REZN";
  level.scr_sound["hero"]["give_covering_fire"] = "Sni1_IGD_317A_REZN";
  level.scr_sound["hero"]["keep_firing"] = "Sni1_IGD_321A_REZN";
  level.scr_sound["hero"]["more_infantry"] = "Sni1_IGD_322A_REZN";
  level.scr_sound["hero"]["mg_2nd_floor"] = "Sni1_IGD_323A_REZN";
  level.scr_sound["hero"]["left_balcony"] = "Sni1_IGD_324A_REZN";
  level.scr_sound["hero"]["more_high_balcony"] = "Sni1_IGD_325A_REZN";
  level.scr_sound["hero"]["friends_moving_up"] = "Sni1_IGD_326A_REZN";
  level.scr_sound["hero"]["up_stairs_quickly"] = "Sni1_IGD_327A_REZN";
  level.scr_sound["hero"]["over_here_lipsmack"] = "Sni1_IGD_328A_REZN";
  level.scr_sound["hero"]["heart_beat_faster"] = "Sni1_IGD_329A_REZN";
  level.scr_sound["hero"]["amsel_soon_insights"] = "Sni1_IGD_330A_REZN";
  level.scr_sound["hero"]["rrrip_vermin"] = "Sni1_IGD_332A_REZN";
  level.scr_sound["hero"]["take_out_ht_mg"] = "Sni1_IGD_333A_REZN";
  level.scr_sound["hero"]["when_our_comrades"] = "Sni1_IGD_334A_REZN";
  level.scr_sound["hero"]["cut_off"] = "Sni1_IGD_335A_REZN";
  level.scr_sound["hero"]["building_wit_flags"] = "Sni1_IGD_336A_REZN";
  level.scr_sound["hero"]["he_will_be_inside"] = "Sni1_IGD_337A_REZN";
  level.scr_sound["hero"]["mudaks_appetite"] = "Sni1_IGD_338A_REZN";
  level.scr_sound["hero"]["vermin_has_no_right"] = "Sni1_IGD_339A_REZN";
  level.scr_sound["hero"]["battle_will_flush"] = "Sni1_IGD_340A_REZN";
  level.scr_sound["hero"]["try_to_call"] = "Sni1_IGD_341A_REZN";
  level.scr_sound["hero"]["he_will_run"] = "Sni1_IGD_342A_REZN";
  level.scr_sound["hero"]["coward_there"] = "Sni1_IGD_343A_REZN";
  level.scr_sound["hero"]["do_not_let"] = "Sni1_IGD_344A_REZN";
  level.scr_sound["hero"]["he_is_behind_truck"] = "Sni1_IGD_345A_REZN";
  level.scr_sound["hero"]["shoot!"] = "Sni1_IGD_347A_REZN";
  level.scr_sound["hero"]["kill_him"] = "Sni1_IGD_348A_REZN";
  level.scr_sound["hero"]["sins_not_go"] = "Sni1_IGD_349A_REZN";
  level.scr_sound["hero"]["quickly!"] = "Sni1_IGD_350A_REZN";
  level.scr_sound["hero"]["good"] = "Sni1_IGD_351A_REZN";
  level.scr_sound["hero"]["very_good"] = "Sni1_IGD_352A_REZN";
  level.scr_sound["hero"]["struck_a_great_blow"] = "Sni1_IGD_353A_REZN";
  level.scr_sound["hero"]["cut_head_from_snake"] = "Sni1_IGD_354A_REZN";
  level.scr_sound["hero"]["run!"] = "Sni1_IGD_357A_REZN";
  level.scr_sound["hero"]["this_way!"] = "Sni1_IGD_358A_REZN";
  level.scr_sound["hero"]["true_marksman"] = "Sni1_IGD_400A_REZN";
  level.scr_sound["hero"]["excel_aim_D"] = "Sni1_IGD_401A_REZN";
  level.scr_sound["hero"]["theyre_retreating"] = "Sni1_IGD_402A_DALE";
  level.scr_sound["hero"]["forward"] = "Sni1_IGD_403A_DALE";
  level.scr_sound["hero"]["charge"] = "Sni1_IGD_404A_DALE";
  level.scr_sound["hero"]["ura"] = "Sni1_IGD_405A_DALE";
  level.scr_sound["hero"]["cover_comrades"] = "Sni1_IGD_406A_REZN";
  level.scr_sound["hero"]["friends_need_cover"] = "Sni1_IGD_407A_REZN";
  level.scr_sound["hero"]["we_not_let"] = "Sni1_IGD_408A_REZN";
  level.scr_sound["hero"]["nothing_wecando"] = "Sni1_IGD_409A_REZN";
  level.scr_sound["hero"]["too_close_to_amsel"] = "Sni1_IGD_410A_REZN";
  level.scr_sound["hero"]["hes_not_alone"] = "Sni1_IGD_411A_REZN";
  level.scr_sound["hero"]["put_bullet_in_bodyguard"] = "Sni1_IGD_412A_REZN";
  level.scr_sound["hero"]["behind_tank"] = "Sni1_IGD_413A_REZN";
  level.scr_sound["hero"]["behind_artillery"] = "Sni1_IGD_414A_REZN";
  level.scr_sound["hero"]["behind_car"] = "Sni1_IGD_415A_REZN";
  level.scr_sound["hero"]["getting_into_car"] = "Sni1_IGD_416A_REZN";
  level.scr_sound["hero"]["shoot_driver"] = "Sni1_IGD_417A_REZN";
  level.scr_sound["hero"]["we_must_go"] = "Sni1_IGD_419A_REZN";
  level.scr_sound["hero"]["before_tank_fires_again"] = "Sni1_IGD_420A_REZN";
  level.scr_sound["hero"]["into_river"] = "Sni1_IGD_421A_REZN";
  level.scr_sound["hero"]["go"] = "Sni1_IGD_422A_REZN";
  level.scr_sound["hero"]["over_here"] = "Sni1_IGD_500A_REZN";
  level.scr_sound["hero"]["they_will_see_you"] = "Sni1_IGD_501A_REZN";
  level.scr_sound["hero"]["stay_close"] = "Sni1_IGD_502A_REZN";
  level.scr_sound["hero"]["try_get_killed"] = "Sni1_IGD_503A_REZN";
  level.scr_sound["hero"]["stay_near"] = "Sni1_IGD_504A_REZN";
  level.scr_sound["hero"]["u_fool"] = "Sni1_IGD_505A_REZN";
  level.scr_sound["hero"]["cant_afford"] = "Sni1_IGD_506A_REZN";
  level.scr_sound["hero"]["nearly_ruined"] = "Sni1_IGD_507A_REZN";
  level.scr_sound["hero"]["sniper_stay_hidden"] = "Sni1_IGD_508A_REZN";
  level.scr_sound["hero"]["dont_draw_attention"] = "Sni1_IGD_509A_REZN";
  level.scr_sound["hero"]["kill_amsel"] = "Sni1_IGD_510A_REZN";
  level.scr_sound["hero"]["move_quietly"] = "Sni1_IGD_511A_REZN";
  level.scr_sound["hero"]["build_with_banners"] = "Sni1_IGD_700A_REZN";
  level.scr_sound["german_redshirt"]["bring_flamer"] = "Sni1_IGD_701A_GER1";
  level.scr_sound["german_redshirt"]["burn_them"] = "Sni1_IGD_702A_GER1";
  level.scr_sound["hero"]["comrades_clearing"] = "Sni1_IGD_703A_REZN";
  level.scr_sound["hero"]["perfect_spot"] = "Sni1_IGD_704A_REZN";
  level.scr_sound["hero"]["hold_fire"] = "Sni1_IGD_705A_REZN";
  level.scr_sound["hero"]["sacrafice"] = "Sni1_IGD_706A_REZN";
  level.scr_sound["hero"]["amsels_death"] = "Sni1_IGD_707A_REZN";
  level.scr_sound["hero"]["hide_tank"] = "Sni1_IGD_708A_REZN";
  level.scr_sound["hero"]["hide_tank2"] = "Sni1_IGD_709A_REZN";
  level.scr_sound["hero"]["hide_truck"] = "Sni1_IGD_710A_REZN";
  level.scr_sound["hero"]["hide_truck2"] = "Sni1_IGD_711A_REZN";
  level.scr_sound["hero"]["hide_flak"] = "Sni1_IGD_712A_REZN";
  level.scr_sound["hero"]["bodyguard_sniper"] = "Sni1_IGD_715A_REZN";
  level.scr_sound["hero"]["bodyguard_firing"] = "Sni1_IGD_716A_REZN";
  level.scr_sound["hero"]["kill_him2"] = "Sni1_IGD_717A_REZN";
  level.scr_sound["hero"]["kill_bodyguard"] = "Sni1_IGD_718A_REZN";
  level.scr_sound["hero"]["hes_running"] = "Sni1_IGD_719A_REZN";
  level.scr_sound["hero"]["hes_on_move"] = "Sni1_IGD_720A_REZN";
  level.scr_sound["hero"]["amsel_running"] = "Sni1_IGD_721A_REZN";
  level.scr_sound["hero"]["failed1"] = "Sni1_IGD_722A_REZN";
  level.scr_sound["hero"]["failed2"] = "Sni1_IGD_723A_REZN";
  level.scr_sound["hero"]["failed3"] = "Sni1_IGD_724A_REZN";
  level.scr_sound["hero"]["armored_car"] = "Sni1_IGD_725A_REZN";
  level.scr_sound["hero"]["keep_moving"] = "Sni1_IGD_726A_REZN";
  level.scr_sound["hero"]["rambov_yell"] = "Sni1_IGD_512A_REZN";
  level.scr_sound["hero"]["just_decoy"] = "Sni1_IGD_800A_REZN";
  level.scr_sound["hero"]["stay_focused"] = "Sni1_IGD_801A_REZN";
  level.scr_sound["hero"]["winged_him"] = "Sni1_IGD_802A_REZN";
  level.scr_sound["hero"]["grazed_him"] = "Sni1_IGD_803A_REZN";
  level.scr_sound["hero"]["he_still_lives"] = "Sni1_IGD_804A_REZN";
  level.scr_sound["hero"]["this_way_coms"] = "Sni1_IGD_805A_DALE";
  level.scr_sound["hero"]["take_positions"] = "Sni1_IGD_806A_DALE";
  level.scr_sound["hero"]["still_die"] = "Sni1_IGD_807A_REZN";
  level.scr_sound["hero"]["noscope"] = "Sni1_IGD_808A_REZN";
  level.scr_sound["hero"]["only_marksman"] = "Sni1_IGD_809A_REZN";
  /
}

officers_sniper_shoot_atyou() {
  if(!flag("player_fired_in_e4")) {
    return;
  }
  if((flag("officer_last_run") || flag("officer_isincar")) && level.difficulty < 3) {
    return;
  }
  shotspot = get_players()[0] getEye();
  firespot = level.officers_sniper gettagorigin("tag_flash");
  chance = 25 * level.difficulty;
  perc = randomint(100);
  if(chance < perc) {
    shotspot = (get_players()[0] getEye()) + (randomint(15), randomint(15), randomint(15));
  }
  vec = firespot - shotspot;
  nvec = vectornormalize(vec);
  playFX(level._effect["fake_rifleflash"], firespot);
  trace = bulletTrace(firespot + (nvec * 5), shotspot, false, undefined);
  bullettracer(firespot + (nvec * 5), shotspot, true);
  wait 0.45;
  magicbullet("mosin_rifle_scoped", firespot + (nvec * 10), shotspot);
}

lookat_notetracks() {
  keys = getarraykeys(level.scr_anim["hero"]);
  for(i = 0; i < keys.size; i++) {
    level thread addNotetrack_customFunction("hero", "look_at", ::lookat_player, keys[i]);
    level thread addNotetrack_customFunction("hero", "look_away", ::lookaway_player, keys[i]);
  }
}

lookat_player(guy) {
  level notify("lookat_safety");
  level endon("lookat_safety");
  level.hero lookatentity(level.player);
  wait 6;
  level thread lookaway_player(guy);
}

lookaway_player(guy) {
  level notify("lookat_safety");
  level.hero lookatentity();
}

#using_animtree("sniper_crows");

hat_anim() {
  level.scr_animtree["hat"] = #animtree;
  level.scr_model["hat"] = "tag_origin_animate";
  level.scr_anim["hat"]["float"] = % o_sniper_ushanka_float;
}

#using_animtree("sniper_crows");

bar_exit() {
  level.scr_animtree["bardoor"] = #animtree;
  level.scr_model["bardoor"] = "tag_origin_animate";
  level.scr_anim["bardoor"]["open"] = % o_sniper_bardoor_open;
}

alley_flamer_fire_control(guy) {
  if(!flag("alley_flamer_flaming")) {
    guy shoot();
    flag_set("alley_flamer_flaming");
  } else {
    guy notify("flame stop shoot");
    guy StopShoot();
    flag_clear("alley_flamer_flaming");
  }
}

crow_rumble_pecks(guy) {
  level.player playrumbleonentity("damage_light");
}

shoo_crow(guy) {
  wait 0.5;
  level notify("player_near_crow");
}

horchhide_cutoff(guy) {
  if(!isDefined(level.horchhide_talk_count)) {
    level.horchhide_talk_count = 0;
  }
  level.horchhide_talk_count++;
  trig = getent("wave_player_fromhorch", "targetname");
  if(!level.player istouching(trig) && level.horchhide_talk_count > 2) {
    level.hero stopanimscripted();
    level notify("horchhide_done");
  }
}

mark_my_words(guy) {
  if(!flag("barfight_ison")) {
    level.hero anim_single_solo(level.hero, "mark_mywords");
  }
}

#using_animtree("sniper_crows");

do_collectible_corpse() {
  wait_for_first_player();
  spot = getstruct("collectible_body_align", "targetname");
  corpse = spawn("script_model", spot.origin);
  corpse character\char_rus_r_ppsh_forsniper::main();
  corpse UseAnimTree(#animtree);
  corpse.angles = spot.angles;
  corpse.animname = "collectible_dude";
  spot anim_single_solo(corpse, "hes_dead");
}

wounded_counter(guy) {
  if(!isDefined(level.woundedcounter)) {
    level.woundedcounter = 520;
  }
  level.woundedcounter = level.woundedcounter + 20;
}